<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DataBase\Model\Model' => __DIR__ .'/src/DataBase/Model/Model.php',
  'DataBase\Model\Table' => __DIR__ .'/src/DataBase/Model/Table.php',
  'DataBase\Module'      => __DIR__ .'/Module.php',
);