<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Testing\Controller\IndexController'  => __DIR__ .'/src/Testing/Controller/IndexController.php',
    'Testing\Controller\RatchetController'=> __DIR__ .'/src/Testing/Controller/RatchetController.php',
    'Testing\Ratchet\Char'                => __DIR__ .'/src/Testing/Ratchet/Chat.php',
    'BaseApp\Module'                      => __DIR__ .'/Module.php',
);