
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>Contamos con médicos especialistas <br />en Medicina Física-Rehabilitación y fisioterapeutas dedicados a la recuperación de pacientes Post ACV.

                                </p></div>
                        </div> 
                        <div id="img"><img src="images/acv.png" width="326" height="435" alt="acv" longdesc="Los accidentes cerebro vasculares son provocados generalmente por una combinación de diferentes factores. Diversos estudios científicos en el Perú, han determinado que uno de cada diez peruanos puede sufrir un Accidente Cerebro Vascular." /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=11" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=11" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=11" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=11" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA ACV Y PARÁLISIS FACIAL</h1></div>


                        <div class="subtitulo"><h2>¿Qué es un Accidente Cerebro Vascular?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>Un derrame cerebral ocurre cuando se produce una interrupción repentina del flujo de sangre a una parte de su cerebro, al no recibir suficiente sangre y oxigeno las células del cerebro pueden dañarse ocasionando un daño permanente. Los accidentes cerebro vasculares son provocados generalmente por una combinación de diferentes factores.</p><p> Diversos estudios científicos en el Perú, han determinado que uno de cada diez peruanos puede sufrir un Accidente Cerebro Vascular. Los Factores de riesgo comunes que conllevan a sufrir un derrame cerebral incluyen:
                            </p>


                        </div> 
                        <div id="lista-especialidad">
                            <div style="margin-left:22px;" class="listita">
                                <ul>
                                    <li>Hipertensión</li>
                                    <li>Fumar</li>
                                    <li>Sedentarismo</li>

                                </ul>
                            </div>
                            <div class="listita">
                                <ul style="margin-bottom:15px;" >
                                    <li>Consumo excesivo de alcohol</li>
                                    <li>El colesterol alto</li>
                                    <li>Obecidad</li>

                                </ul>
                            </div>

                            <div style="margin-top:15px;" class="texto-int"><p>Como se puede ver en la lista anterior, hay muchos factores de riesgo que usted puede cambiar. Si usted ha sufrido de un accidente cerebro vascular le recomendamos que visite a un especialista lo más pronto posible. <span class="resaltado"><strong>En el Centro Médico Especializado OSI, contamos con médicos especialistas en Medicina Física y Rehabilitación y fisioterapeutas dedicados a la recuperación de pacientes Post ACV.</strong></span>
                                </p>

                            </div> 

                        </div>

                        <div class="subtitulo"><h2>¿Cómo puede ayudarle la fisioterapia en OSI?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int"><p>La primera prioridad es que su condición sea médicamente estable, una vez que esto ha ocurrido podemos determinar qué enfoque va a tener su rehabilitación. Sus sesiones de fisioterapia estarán a cargo de un equipo multidisciplinario que pueden ser el médico fisiatra, el terapeuta físico, el de lenguaje y el de terapia ocupacional.
                            </p>
                            <p style="margin-top:10px;" >La fisioterapia y rehabilitación, por lo general, comienza en los primeros días después del accidente cerebrovascular. <span class="resaltado"><strong>El papel del fisioterapeuta estará en ayudarle a devolver la mayor funcionabilidad posible a su cuerpo para que pueda seguir haciendo las cosas que le gustan en la vida.</strong></span>
                            </p>

                            <p style="margin-top:10px;" >Sus sesiones de fisioterapia y rehabilitación pueden variar según la gravedad y evolución del paciente y los problemas resultantes del accidente cerebro vascular. Sus sesiones podrían incluir:
                            </p>

                        </div>



                        <div style="margin-left:18px;width:628px;" class="listita">
                            <ul style="width:628px;" >
                                <li style="width:550px;" >Aplicación de equipos fisioterapéuticos y masajes para estimular las zonas afectadas.</li>
                                <li style="width:550px;margin-top:2px;" >Enseñarle el volver a aprender cómo realizar los movimientos básicos, tales como levantarse de la cama 
                                    y caminar.</li>
                                <li style="width:590px;margin-top:2px" >Enseñarle ejercicios específicos para ayudarle en su recuperación mediante el fortalecimiento de los músculos débiles, mejorando el equilibrio y la enseñanza nuevas maneras de completar tareas.</li>
                                <li style="width:590px;margin-top:2px;" >Enseñarle cómo utilizar cualquier equipo que pueda ser necesario para ayudar a cumplir su tareas 
                                    cotidianas. </li>
                            </ul>
                        </div>  
                        <div style="margin-top:3px;" class="texto-int"><p>Cada paciente puede presentar problemas diferentes después de un ACV. La velocidad de recuperación depende de la severidad y ubicación de las zonas afectadas.<span class="resaltado"> <strong>En OSI contamos con un programa que combina las mejores prácticas de la fisioterapia y acupuntura, en donde nos preocupamos por una recuperación basada en tres pilares: recuperación motora, sensorial y motora visceral.</strong></span> Nuestro objetivo principal es recuperar la movilidad, sensibilidad y recuperar la mayor funcionabilidad posible de nuestros pacientes. 
                            </p>
                            <p style="margin-top:10px;" >Su mejor oportunidad para recuperarse después de un ACV es recibiendo fisioterapia y rehabilitación de forma oportuna. También, es importante que se mantenga motiva y seguir haciendo los ejercicios que su especialista le ha enseñado; necesita ser como un atleta que necesita empujarse a sí mismo para mejorar.
                            </p>
                        </div>
                        <div style="margin-bottom:30px;" id="consulte">
                            <p style="margin-top:109px;" >Si usted<span class="color-celeste"> ha sufrido de un ACV y requiere atención, llámenos,</span> nuestros especialistas gustosamente le pueden atender.</p>
                        </div>    
                    </div>
                </div>