
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div style="margin-top:30px;" id="tex-nube"><p> La fisioterapia puede ayudarles <br />a lidiar con el dolor y la discapacidad causada por esta enfermedad. 

                                </p></div>
                        </div> 
                        <div id="img"><img src="images/artritis.png" width="326" height="445" alt="artritis" longdesc="Debido a que  no existe cura para " /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=7" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=7" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=7" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=7" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA ARTRITIS REUMATOIDEA</h1></div>


                        <div class="subtitulo"><h2>Tratamiento
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int"><p>Muchos pacientes encuentran en la fisioterapia para artritis una parte esencial de su recuperación. La fisioterapia puede ayudarles a lidiar con el dolor y la discapacidad causada por esta enfermedad. 

                                Debido a que no existe una cura para la artritis, el enfoque del tratamiento es el manejo de la enfermedad.</p>
                            <p><strong><span class="resaltado">En el Centro Médico Especializado OSI creemos que la base del éxito del tratamiento fisioterapéutico es primero la definición de metas entre el médico especialista, el fisioterapeuta y el paciente.</span></strong> </p> 
                            <p>Durante el desarrollo del programa terapéutico las condiciones de las articulaciones del paciente (incluyendo la resistencia, flexibilidad y la deformidad), así como la fuerza muscular y la resistencia física son analizadas en detalle para poder fijar un plan de tratamiento acorde a las necesidades del paciente. Al establecer metas y realizar su fisioterapia de forma constante, los pacientes por lo general pueden mejorar su capacidad para realizar actividades de la vida diaria.
                            </p>
                        </div> 
                        <div class="subtitulo"><h2>El Ejercicio es Beneficioso para los Pacientes con Artritis Reumatoidea
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int"><p>Un plan de ejercicios adecuado puede reducir el dolor en las articulaciones y rigidez, al tiempo que mejora la fuerza muscular, la flexibilidad articular, el equilibrio, la coordinación y la resistencia. Durante sus sesiones de fisioterapia para artritis, <span class="resaltado"><strong>un especialista le enseñará a realizar ejercicios de amplitud de movimiento, ejercicios de fortalecimiento y ejercicios aeróbicos.</strong></span>
                            </p>
                        </div> 
                        <div class="subtitulo"><h2>Técnicas de Protección de las Articulaciones
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int"><p>La protección de las articulaciones es fundamental para mejorar la movilidad y disminuir el riesgo de deformidad de la articulación. Es importante evitar el estrés innecesario y la tensión en las articulaciones. <span class="resaltado"><strong>Para reducir el estrés en las articulaciones, los pacientes deben tratar de mantener o mejorar la fuerza muscular.</strong></span> Durante sus sesiones de fisioterapia, le enseñaremos cómo cuidar sus articulaciones para evitar el dolor.
                            </p>
                        </div>
                        <div class="subtitulo"><h2>Mécanica Corporal Adecuada para Artritis Reumatoidea
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int"><p>La mecánica corporal se refiere a cómo una persona se mueve. Durante sus sesiones de fisioterapia para artritis, le daremos consejos ergonómicos que le ayudaran a tener una postura corporal correcta para evitar o reducir el dolor articular y muscular, el estrés y la tensión en las articulaciones , y el riesgo de lesión.
                            </p>
                        </div>
                    </div>
                </div>