
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>La fisioterapia en OSI está enfocada <br />en restablecer el funcionamiento normal de la rodilla y en eliminar el dolor causado por la lesión.
                                </p></div>
                        </div> 
                        <div id="img"><img src="images/dolor-rodilla.png" width="326" height="433" alt="dolor-rodilla" longdesc="La lesión del ligamento de rodilla se pueden dar después de aterrizar mal de un salto, de mover la pierna bruscamente o después que la rodilla ha sufrido un duro golpe, como cuando se juega futbol. " /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=13" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=13" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=13" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=13" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA DOLOR DE RODILLA</h1></div>


                        <div class="subtitulo"><h2>¿Qué es un ligamento de la rodilla?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>Un ligamento es una pequeña banda de tejido conjuntivo resistente y fibrosa compuesta principalmente de moléculas largas y fibrosas de colágeno. Los ligamentos conectan los huesos a otros huesos en y alrededor de las articulaciones. La función de los ligamentos es limitar la movilidad de una articulación para prevenir un mal movimiento o varios movimientos a la vez que puedan causar una lesión.</p>
                            <p style="margin-top:10px;" >La lesión del ligamento de rodilla se pueden dar después de aterrizar mal de un salto, de mover la pierna bruscamente o después que la rodilla ha sufrido un duro golpe, como cuando se juega futbol. Por lo general, las lesiones se producen con un hecho que implica velocidad; mientras que la debilidad muscular o falta de coordinación pueden predisponer a un esguince de ligamentos o desagarro. </p></div>

                        <div class="subtitulo"><h2>Síntomas según Gravedad de Lesión del Ligamento de Rodilla
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>La gravedad y los síntomas de un esguince de ligamento depende del grado de estiramiento o desgarro del ligamento. </p>


                        </div> 

                        <div class="dolor"><p>GRADO LEVE</p></div>
                        <div class="texto-dolor"><p>En un grado leve me esguince, los ligamentos de la rodilla pueden estirarse sin romperse. Aunque no sienta dolor fuerte o no se hinche tanto, un esguince leve puede aumentar el riesgo de una lesión en el futuro.</p></div> 
                        <div class="dolor2"><p>GRADO MODERADO</p></div>
                        <div class="texto-dolor"><p style="margin-top:5px;" >En un grado moderado, el esguince de grado II es un desgarro parcial los ligamentos, causando inflamación, moretones y haciendo que el uso de la articulación sea dolorosa.</p></div> 
                        <div class="dolor"><p style="margin-left:25px;" >GRADO SEVERO</p></div>
                        <div class="texto-dolor"><p>En un grado severo, el esguince de grado III es una rotura completa del ligamento, causando hinchazón y a veces sangrado por debajo de la piel. Como resultado, la articulación se vuelve inestable y no puede soportar peso. </p></div>  

                        <div style="margin-top:20px;" class="subtitulo"><h2>¿Cómo puede ayudarle la fisioterapia y rehabilitación en OSI?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p><strong><span class="resaltado">La fisioterapia en OSI está enfocada en restablecer el funcionamiento normal de la rodilla y en eliminar el dolor causado por la lesión.</span></strong> Dependiendo de la gravedad de la lesión de los ligamentos en la rodilla y los avances que presente al tratamiento, el tratamiento de fisioterapia puede variar. </p>
                            <p style="margin-top:10px;" >Su fisioterapeuta le puede ayudar a restaurar pleno movimiento y también le enseñará cómo prevenir lesiones recurrentes. El tratamiento incluirá la aplicación de equipos médicos, masajes terapéuticos y un programa de ejercicios, posiblemente con el uso de algunos equipos de gimnasio para aumentar su fuerza y coordinación, y restaurar cualquier movimiento perdido en la articulación.</p></div>
                        <div id="consulte3">
                            <p>Si usted ha sufrido de una lesión de los ligamentos ligamento en la rodilla, llámenos, nuestros especialistas estarán gustosos de poder atenderle y solucionar su dolencia. </p>
                        </div>    
                    </div>
                </div>