
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>Nuestro tratamiento está enfocado<br />
                                    en eliminar el dolor y ayudarle a<br /> 
                                    recuperar la fucionabilidad de <br />
                                    su espalda

                                </p></div>
                        </div> 
                        <div id="img"><img src="images/dolor-espalda.png" width="321" height="415" alt="dolor-espalda" longdesc="Existen muchas causas que provocan el dolor de espalda; sin embargo, para cada una de ellas la fisioterapia puede encontrar la forma más eficaz de eliminar su dolor. " /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=9" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=9" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=9" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=9" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA DOLOR DE ESPALDA</h1></div>



                        <div style="margin-top:0px;" class="texto-int">
                            <p>La fisioterapia puede ser el tratamiento que marque el fin de su dolor de espalda.<span class="resaltado"> <strong>Nuestro  tratamiento está enfocado en eliminar el dolor y ayudarle a recuperar la funcionabilidad de su espalda.</strong></span> Lo más importante después de sus sesiones es que el fisioterapeuta le puede enseñar a  cómo prevenir el dolor de espalda en el futuro.
                            </p>
                            <p style="margin-top:10px;" >Existen muchas causas que provocan el dolor de espalda; sin embargo, para cada una de ellas la fisioterapia puede encontrar la forma más eficaz de eliminar su dolor.<span class="resaltado"><strong> Si el dolor de espalda tiene un impacto en sus actividades diarias, incluyendo las de su hogar, el deporte, el trabajo e inclusive al caminar puede que necesite visitar a un especialista.</strong></span>
                            </p>
                            <p style="margin-top:10px;" >En el Centro Médico Especializado OSI, diseñado un plan terapéutico que combina las mejores prácticas de la fisioterapia gracias a la experiencia de haber atendido a más de 15,000 pacientes.
                            </p>

                        </div>

                        <div style="width:600px;margin-top:-10px;" id="lista-especialidad">
                            <div style="margin-left:22px;width:600px;" class="listita">
                                <ul style="width:600px;" >
                                    <li style="width:550px;" ><span class="text-celeste">Dolor de Espalda Agudo:</span> dura menos de seis semanas.</li>
                                    <li style="width:550px;margin-top:2px;" ><span class="text-celeste">Dolor de Espalda Sub agudo:</span> duración de seis semanas a tres meses.</li>
                                    <li style="width:590px;margin-top:2px" ><span class="text-celeste">Dolor de Espalda Crónico:</span> duración de más de tres meses. </li>

                                </ul>
                            </div>
                        </div>
                        <div style="margin-top:20px;" class="subtitulo"><h2>¿Qué puede hacer el fisioterapeuta?
                            </h2></div>
                        <div style="width:600px;" class="lista-especialidad">
                            <div style="margin-left:22px;width:600px;" class="listita">
                                <ul style="width:600px;" >
                                    <li style="width:550px;" >Evaluar y diseñar un tratamiento especifico para según la causa del dolor de espalda.</li>
                                    <li style="width:550px;margin-top:2px;" >Realizar el tratamiento con equipos de avanzada tecnología. </li>
                                    <li style="width:590px;margin-top:2px" >Realizar manipulaciones manuales para aliviar el dolor de espalda.</li>
                                    <li style="width:590px;margin-top:2px;" >Enseñarte ejercicios específicos de fortalecimiento y flexibilidad.</li>
                                    <li style="width:590px;margin-top:2px;" >Enseñarte ejercicios para mejorar tu postura.</li>
                                    <li style="width:590px;margin-top:2px;" >Enseñarte formas de prevenir futuros problemas de espalda.</li>
                                    <li style="width:590px;margin-top:2px;" >Evaluar tu lugar de trabajo, hacer un análisis y darte asesoramiento para realizar tus tareas de una manera ergonómica. </li>
                                </ul>
                            </div>
                        </div>
                        <div id="consulte2">
                            <p>Si usted<span class="color-celeste"> sufre de dolor de espalda, no lo dude. Puede llamarnos y consultar por uno de nuestros especialistas. </span>Gustosamente lo vamos a atender. </p>
                        </div>    
                    </div>
                </div>