
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>Nuestro tratamiento está enfocado <br />en eliminar y evitar dolores futuros y el empeoramiento de la curvatura de la columna vertebral.

                                </p></div>
                        </div> 
                        <div id="img"><img src="images/escoliosis.png" width="340" height="415" alt="escoliosis" longdesc="La escoliosis es una curva lateral o hacia los lados en la columna vertebral que es aparente cuando se ve desde atrás de la columna vertebral." /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=14" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=14" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=14" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=14" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA ESCOLIOSIS</h1></div>


                        <div class="subtitulo"><h2>¿Qué es la Escoliosis?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>La escoliosis es una curva lateral o hacia los lados en la columna vertebral que es aparente cuando se ve desde atrás de la columna vertebral. La mayoría de los casos de escoliosis son leves, pero la escoliosis severa puede ser incapacitante. </p><p>Un grado leve de escoliosis es frecuente y ocurre hasta en el 50% de la población. La escoliosis por lo general no requiere de ningún tratamiento específico a menos que sea dolorosa o tensa. Sin embargo, en los casos graves, un tratamiento de fisioterapia de forma oportuna puede evitar dolores y problemas de espalda futuros.
                            </p>
                            <p style="margin-top:10px;" >Si bien las causas para la mayoría de tipos de escoliosis son desconocidas, el factor hereditario es una factor común en personas que sufren de escoliosis. </p>

                            <p style="margin-top:10px;" >Algunos tipos menos comunes de escoliosis pueden ser causados por: </p>
                        </div>




                        <div class="dolor"><p style="font-size:12px; text-align:center;margin-left:10px;width:139px;margin-top:9px;" >UNA PIERNA MAS CORTA QUE LA OTRA</p></div>
                        <div class="texto-dolor"><p style="margin-top:11px;line-height:18px;margin-left:18px; ">La curvatura de la columna vertebral puede desarrollarse debido a problemas en otras partes del cuerpo, como una pierna más corta que las otras o espasmos musculares en la espalda.</p></div> 
                        <div class="dolor2"><p style="font-size:12px; text-align:center;margin-left:10px;width:139px;margin-top:9px;" >TRASTORNOS
                                NEUROMUSCULARES</p></div>
                        <div class="texto-dolor"><p style="margin-top:13px;line-height:18px;margin-left:18px; " >Como la parálisis cerebral, defectos de nacimiento que afectan el desarrollo de la columna vertebral y la distrofia muscular pueden causar escoliosis.</p></div> 
                        <div class="dolor"><p style="font-size:12px; text-align:center;margin-left:10px;width:139px;margin-top:9px;" >ARTRITIS EN LA 
                                COLUMNA VERTEBRAL</p></div>
                        <div class="texto-dolor"><p style="margin-top:11px;line-height:18px;margin-left:18px; " >La escoliosis degenerativa ocurre que por lo general ocurre en los adultos mayores, debido al debilitamiento de los ligamentos y otros tejidos blandos de la columna.</p></div>  

                        <div style="margin-top:20px;" class="subtitulo"><h2>¿Cómo puede ayudarle la fisioterapia y rehabilitación en OSI?
                            </h2></div>
                        <div class="texto-int">
                            <p>En el Centro Médico Especializado OSI creemos que la parte más importante del tratamiento para escoliosis es la detección temprana de su presencia, ya que el tratamiento temprano puede evitar la necesidad de una cirugía. El tratamiento puede variar según la gravedad de la escoliosis, la edad y estilo de vida del paciente. </p><p> <span class="resaltado"><strong>Antes de iniciar el tratamiento nuestros especialistas evalúan una serie de parámetros antes de decidir el plan terapéutico más adecuado.</strong></span> En la mayoría de los casos una escoliosis leve no requiere tratamiento específico; sin embargo un fisioterapeuta le puede enseñar algunos ejercicios beneficiosos para su espalda y columna vertebral. </p>
                            <p style="margin-top:10px;" ><span><strong>En OSI contamos con un tratamiento multidisciplinario que combina la fisioterapia y la quiropráctica computarizada.</strong></span> Además, un asesoramiento en cuanto a la postura, la enseñanza de ejercicios y consejos ergonómicos nos permite ofrecer a nuestros pacientes un tratamiento integral enfocado en eliminar y evitar dolores futuros y el empeoramiento de la curvatura de la columna vertebral. </p></div>


                        <div id="consulte">
                            <p><span class="color-celeste">Si usted sufre de escoliosis, no lo dude, puede consultar con nuestros médicos especialistas.</span> Llámenos, gustosamente podemos resolver sus dudas y ayudarle a solucionar su dolencia. </p>
                        </div>
                    </div>
                </div>