
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>Te ayudamos a manejar la <br />fibromialgia para que puedas continuar <br /> con una vida activa y haciendo las cosas que más disfrutas. 
                                </p></div>
                        </div> 
                        <div id="img"><img src="images/fibromialgia.png" width="340" height="415" alt="fibromialgia" longdesc="Las personas con fibromialgia tienen puntos de dolor en el cuerpo que pueden ser en el cuello, los hombros, los brazos, la espalda, la cadera y las piernas. " /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=10" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=10" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=10" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=10" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA FIBROMIALGIA</h1></div>


                        <div class="subtitulo"><h2>¿Qué es la Fibromialgia?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>La fibromialgia es una enfermedad que provoca dolor y cansancio muscular. Las personas con fibromialgia tienen puntos de dolor en el cuerpo que pueden ser en el cuello, los hombros, los brazos, la espalda, la cadera y las piernas. Estos puntos de dolor son súper sensibles y pueden causar una gran molestia si es que son presionados. </p>

                            <div class="subtitulo"><h2>¿Cómo te puede ayudar un fisioterapeuta?
                                </h2></div>
                            <div style="margin-top:3px;" class="texto-int">
                                <p><strong><span class="resaltado">Un fisioterapeuta puede ayudarte a mejorar tu calidad de vida y enseñarte a manejar la fibromialgia para que puedas continuar con una vida activa y haciendo las cosas que más disfrutas.</span></strong> Un fisioterapeuta puede:  </p>


                            </div> 
                            <div id="lista-especialidad">

                                <div style="margin-left:18px;width:600px;" class="listita">
                                    <ul style="width:600px;" >
                                        <li style="width:550px;" >Crear un plan terapéutico diseñado en aliviar el dolor.</li>
                                        <li style="width:550px;margin-top:2px;" >Enseñarte ejercicios para recuperar tu vitalidad y energía. </li>
                                        <li style="width:590px;margin-top:2px" >Enseñarte a mantenerte activo e independiente.</li>

                                    </ul>
                                </div>
                            </div>

                            <div style="margin-top:3px;" class="texto-int">
                                <p style="margin-top:10px;" >En OSI hemos tratado diversos casos de fibromialgia con excelentes resultados. El dolor en la fibromialgia está presente en los tejidos blandos de todo el cuerpo y se pueden concentrar en lugares como el cuello y la espalda baja. 
                                </p>
                                <p style="margin-top:10px;" ><strong><span class="resaltado">En OSI, creemos que el primer paso para un buen tratamiento es el entendimiento de que esta enfermedad es compleja y puede llegar a ser frustrante.</span></strong> El éxito del tratamiento es en gran medida un esfuerzo conjunto entre el médico, el fisioterapeuta y el paciente desde un inicio.</p>
                                <p style="margin-top:10px;" >Usted debe estar dispuesto a hacer cambios de estilo de vida, así como prestar atención a su salud psicológica para ayudar a controlar los síntomas. Si usted cree que tiene fibromialgia o ya tiene el diagnostico y está en búsqueda de un tratamiento, consulte con nuestros especialistas. Llámenos, gustosamente le podemos atender.  </p>

                            </div>

                            <div id="consulte3">
                                <p style="width:450px;margin-top:99px;margin-left:150px;font-size:15px;" >Si usted <span class="text-celeste">sufre de artritis, dolores articulares o dolores musculares crónicos;</span> no lo dude, llámenos. <span class="text-celeste">En OSI tenemos médicos y fisioterapeutas altamente capacitados</span> para la fisioterapia y rehabilitación de personas como usted.</p>
                            </div>    
                        </div>
                    </div>
                </div>
