
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p> En OSI contamos con un plan terapéutico integral para ayudarle a restablecer el movimiento de la zona afectada.

                                </p></div>
                        </div> 
                        <div style="margin-left:-22px;" id="img"><img src="images/lesion-articular.png" width="365" height="415" alt="lesion-articular" longdesc="La mejor manera de prevenir un desgarro musculares y las lesiones articulares es un programa de calentamiento antes de comenzar cualquier ejercicio" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=15" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=15" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=15" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=15" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA LESIÓN ARTICULAR</h1></div>


                        <div class="subtitulo"><h2>¿Qué son los Desgarro Musculares y Lesiones Articulares?
                            </h2></div>
                        <div style="margin-top:3px;" class="texto-int">
                            <p>Los desgarros musculares y lesiones articulares son un tipo de lesión muy común. Pueden ocurrir cuando se estira o extiende el musculo más allá de su rango normal, mientras corremos, jugamos nuestro deporte favorito o hacemos un trabajo de jardinería. Un desgarro muscular puede ser leve o grave dependiendo de cuanto haya afectado al musculo y las articulaciones relacionadas a la zona.
                            </p>
                            <p style="margin-top:10px;" >La mejor manera de prevenir un desgarro musculares y las lesiones articulares es un programa de calentamiento antes de comenzar cualquier ejercicio y, a continuación, enfriar y estirar cuando haya terminado la actividad. Sin embargo, si usted ya está lesionado, no se preocupe, en el Centro Médico Especializado OSI contamos con un plan terapéutico integral diseñado según la gravedad de la lesión, sus necesidades, sexo, estilo de vida y edad.</p>

                        </div>
                        <div class="subtitulo"><h2>¿Cómo puede ayudarle la fisioterapia y rehabilitación en OSI?
                            </h2></div>
                        <div class="texto-int">
                            <p><strong><span class="resaltado">En OSI creemos que un tratamiento temprano es la clave de una recuperación optima, entre más pronto reciba la ayuda, más rápido podrá sanar.</span></strong> El tratamiento de fisioterapia puede incluir el trabajo con equipos médicos especializados, manipulaciones manuales y ejercicios para ayudarle a restablecer el movimiento de la zona afectada.  </p>
                            <p style="margin-top:10px;" >Algunos tipos menos comunes de escoliosis pueden ser causados por:</p></div>

                        <div style="width:600px;margin-top:-10px;" id="lista-especialidad">
                            <div style="margin-left:22px;width:600px;" class="listita">
                                <ul style="width:600px;" >
                                    <li style="width:550px;" ><span class="text-celeste">Descansar:</span> detener la actividad que está haciendo para evitar más daños.</li>
                                    <li style="width:550px;margin-top:2px;" ><span class="text-celeste">Enfriar:</span> Envolver la zona con hielo picado en una toalla húmeda sobre el área lesionada durante 20 minutos cada 2 horas..</li>
                                    <li style="width:590px;margin-top:2px" ><span class="text-celeste">Comprimir:</span> Vendar de manera firma la zona para reducir la hinchazón. </li>
                                    <li style="width:590px;margin-top:2px;" ><span class="text-celeste">Elevar:</span> Mantenga el área afectada elevada tanto como sea posible</li>
                                    <li style="width:590px;margin-top:2px;" ><span class="text-celeste">Diagnosticar:</span> Es muy importante consultar a su médico o fisioterapeuta si el dolor y la inflamación empeora.</li>
                                </ul>
                            </div>

                            <div class="texto-int">
                                <p>Y evite durante las primeras 72 horas:</p>
                            </div>

                            <div id="lista-especialidad">
                                <div style="margin-left:22px;margin-top:0px;" class="listita">
                                    <ul>
                                        <li>Calor</li>
                                        <li>Alcohol</li>
                                        <li>Correr (o cualquier ejercicio)</li>
                                        <li>Masaje</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div id="consulte2">
                            <p>Si usted <span class="color-celeste">ha sufrido de una lesión muscular o articular. No lo dude, puede llamar a nuestros especialistas</span> y consultar por el<span class="color-celeste"> mejor tratamiento.</span></p>
                        </div>    
                    </div>
                </div>