
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div style="margin-top:16px;" id="tex-nube"><p>Contamos con un tratamiento multidisciplinario que le ayudará a recuperarse de su lesión y le enseñará cómo alcanzar su máximo <br /> performance.
                                </p></div>
                        </div> 
                        <div id="img"><img src="images/lesion-deportiva.png" width="346" height="435" alt="lesion-deportiva" longdesc="Las lesiones deportivas más comunes están a la cabeza, los hombros, los isquiotibiales, las rodillas y los tobillos" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=12" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=12" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=12" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=12" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA LESIONES DEPORTIVAS</h1></div>



                        <div style="margin-top:0px;" class="texto-int">
                            <p>Las lesiones deportivas más comunes están a la cabeza, los hombros, los isquiotibiales, las rodillas y los tobillos. La mayoría de las lesiones deportivas se pueden prevenir fácilmente y un fisioterapeuta puede enseñarle cómo. Sin embargo, si usted está lesionado nuestros especialistas en fisioterapia y rehabilitación también pueden ayudarle. <span class="resaltado"><strong>En el Centro Médico Especializado OSI, contamos con un tratamiento multidisciplinario que le ayudará a recuperarse de su lesión y le enseñará cómo alcanzar su máximo performance.</strong></span>
                            </p>

                        </div>



                        <div class="subtitulo"><h2>¿Cuándo debo consultar un fisioterapeuta ?
                            </h2></div>

                        <div style="margin-top:-6px;" class="texto-int">
                            <p>Como pauta general, usted debe ver a un fisioterapeuta si:
                            </p>

                        </div>


                        <div style="width:600px;" class="lista-especialidad">
                            <div style="margin-left:22px;width:600px;" class="listita">
                                <ul style="width:600px;" >
                                    <li style="width:550px;" >No puede seguir su rutina deportiva normal</li>
                                    <li style="width:550px;margin-top:2px;" >Su lesión es recurrente</li>
                                    <li style="width:590px;margin-top:2px" >Tiene dolor muscular o ha perdido rango articular</li>

                                </ul>
                            </div>
                        </div>

                        <div style="margin-top:15px;" class="texto-int">
                            <p>Durante su primera visita a OSI, nuestros especialistas le preguntarán sobre su deporte y la forma en cómo se hizo la lesión, su historial médico y otros datos relacionados. Además, realizarán un examen físico completo y un examen de la parte del cuerpo lesionada.

                            </p>
                            <p style="margin-top:10px;" ><strong><span class="resaltado">En base a los resultados de la evaluación de fisioterapia el análisis de sus necesidades particulares, y sus metas, diseñaremos un plan de tratamiento integral hecho específicamente para usted. </span></strong>Su tratamiento puede comenzar inmediatamente después de la evaluación inicial y por lo general se indicará un número inicial de sesiones a seguir. 

                            </p>

                            <p style="margin-top:10px;" >Usted se beneficiará de la experiencia multidisciplinaria de nuestro equipo, en uno de los centros médicos especializados en fisioterapia más grandes y de mayor éxito en Lima. Con una estrecha relación con médicos cirujanos, fisiatras y terapeutas físicos y otros profesionales de la salud, usted nunca estará lejos de la ayuda del experto que usted necesita.
                            </p>
                        </div>
                        <div id="consulte2">
                            <p style="margin-top:109px;" >Si usted<span class="color-celeste"> está lesionado o buscar aumentar su rendimiento; llámenos,</span> nuestros especialistas en fisioterapia gustosamente le pueden atender. </p>
                        </div>    
                    </div>
                </div>