
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube"><p>Nuestro objetivo es recuperar la movilidad, disminuir la inflamación y eliminar el dolor
                                    través de ejercicios y 
                                    hábitos de trabajo.

                                </p></div>
                        </div> 
                        <div id="img"><img src="images/tendinitis.png" width="345" height="429" alt="tendinitis" longdesc="La mayoría de expertos creen que la tendinitis; es a menudo causada por un movimiento repetitivo mal hecho o el uso excesivo de las articulaciones." /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ENFERMEDADES Y DOLENCIAS</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=8" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=8" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=8" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=8" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA  PARA TENDINITIS</h1></div>



                        <div style="margin-top:0px;" class="texto-int">
                            <p><strong><span class="resaltado">En OSI hemos tratado varios casos de tendinitis con excelentes resultados clínicos.</span></strong> Al realizar el tratamiento de fisioterapia nuestro objetivo principal es recuperar la movilidad, disminuir la inflamación y eliminar el dolor. 
                            </p>
                            <p style="margin-top:10px;" >La tendinitis es una condición muy dolorosa que a menudo aflige a los tendones del codo, el hombro, la cadera y la rodilla. La mayoría de expertos creen que la tendinitis; es a menudo causada por un movimiento repetitivo mal hecho o el uso excesivo de las articulaciones. Los síntomas incluyen dolor crónico o recurrente, inflamación, entumecimiento y la inmovilidad de la zona afectada. 

                            </p>
                            <p style="margin-top:10px;" ><strong><span class="resaltado">Durante sus sesiones de fisioterapia un especialista le puede enseñar a manejar su condición a través de ejercicios y hábitos de trabajo. </span></strong>También, se le aplicará tratamiento con diversos equipos médicos como el laser, luz infrarroja, ultrasonido, entre otros que promueven la recuperación del tejido muscular y articular. 
                            </p>
                            <p style="margin-top:10px;" >En caso de sufrir un caso complicado de tendinitis aguda o crónica que no se alivie con la fisioterapia; <span class="resaltado"><strong>en el Centro Médico Especializado OSI contamos con la más moderna tecnología médica; las ondas de choque.</strong></span> </p><p>Diversos estudios, han demostrado que las sesiones de ondas de choque pueden lograr una disminución significativa del dolor en las primeras sesiones; en muchos casos el dolor disminuye hasta en un 80% después de la tercera sesión.  

                            </p>

                        </div>



                        <div class="subtitulo"><h2>En OSI somos especialistas en tratar las siguientes patologías relacionadas a la tendinitis y 
                                calcificaciones:
                            </h2></div>
                        <div style="width:600px;" class="lista-especialidad">
                            <div style="margin-left:22px;width:600px;" class="listita">
                                <ul style="width:600px;" >
                                    <li style="width:550px;" >Tendinitis con o sin calcificación de hombro</li>
                                    <li style="width:550px;margin-top:2px;" >Tendinitis Patelar</li>
                                    <li style="width:590px;margin-top:2px" >Tendinitis de Tendón de Aquiles</li>
                                    <li style="width:590px;margin-top:2px" >Tendinitis Trocantérea (Cadera)</li>
                                    <li style="width:590px;margin-top:2px" >Bursitis Calcificada / Trocantérea.</li>
                                    <li style="width:590px;margin-top:2px" >Cubital / Medial (Codo Golfista)</li>
                                    <li style="width:590px;margin-top:2px" >Epicondilitis Radial / Lateral (Codo de Tenista)</li>
                                    <li style="width:590px;margin-top:2px" >Enfermedad de Dupuytren y enfermedad de Quervain</li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>