<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Session\Form\Login'          => __DIR__ .'/src/Session/Form/Login.php',
    'Session\Service\Login'       => __DIR__ .'/src/Session/Service/Login.php',
    'Session\View\Helper\Session' => __DIR__ .'/src/Session/View/Helper/Session.php',
    'Session\Module'              => __DIR__ .'/Module.php',
);