<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Payments\BaseService\PEService'             => __DIR__ .'/src/Payments/BaseService/PEService.php',
    'Payments\Controller\PagoEfectivoController' => __DIR__ .'/src/Payments/Controller/PagoEfectivoController.php',
    'Payments\Service\PECrypto'     => __DIR__ .'/src/Payments/Service/PECrypto.php',
    'Payments\Service\PEXmlRequest' => __DIR__ .'/src/Payments/Service/PEXmlRequest.php',
    'Payments\Service\PagoEfectivo' => __DIR__ .'/src/Payments/Service/PagoEfectivo.php',
    'Payments\Module'      => __DIR__ .'/Module.php',
);