<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'BaseApp\Controller\PortalController'=> __DIR__ .'/src/BaseApp/Controller/PortalController.php',
  'BaseApp\Module'                     => __DIR__ .'/Module.php',
);