
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>

        <!-- jQuery 2.1.3 -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <!-- Bootstrap 3.3.2 JS -->
        <script src="<?php echo $this->portal('admlte');?>/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- SlimScroll -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/slimScroll/jquery.slimScroll.min.js" type="text/javascript"></script>
        <!-- FastClick -->
        <script src='<?php echo $this->portal('admlte');?>/plugins/fastclick/fastclick.min.js'></script>
        <!-- AdminLTE App -->
        <script src="<?php echo $this->portal('admlte');?>/dist/js/app.min.js" type="text/javascript"></script>
        
        <?php if(TRUE): // Is Dashboard?>
        <!-- Sparkline -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <!-- jvectormap -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->portal('admlte');?>/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
        <!-- daterangepicker -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <!-- datepicker -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <!-- iCheck -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <!-- ChartJS 1.0.1 -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/chartjs/Chart.min.js" type="text/javascript"></script>
        <!-- AdminLTE dashboard demo (This is only for demo purposes) 
        <script src="<?php echo $this->portal('admlte');?>/dist/js/pages/dashboard2.js" type="text/javascript"></script>-->
        <!-- AdminLTE for demo purposes -->
        <script src="<?php echo $this->portal('admlte');?>/dist/js/demo.js" type="text/javascript"></script>
        <?php endif; ?>
        
        <?php if(TRUE): // Is Dashboard?>
        <!-- InputMask -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
        <script src="<?php echo $this->portal('admlte');?>/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
        <script src="<?php echo $this->portal('admlte');?>/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        <!-- SlimScroll 1.3.0 -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/slimScroll/jquery.slimScroll.min.js" type="text/javascript"></script>
        <!-- iCheck 1.0.1 -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <!-- FastClick -->
        <script src='<?php echo $this->portal('admlte');?>/plugins/fastclick/fastclick.min.js'></script>
        
        <!-- Page script -->
        <script type="text/javascript">
        $(function () {
          //Datemask dd/mm/yyyy
          $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
          //Datemask2 mm/dd/yyyy
          $("#datemask2").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
          //Money Euro
          $("[data-mask]").inputmask();

          //Date range picker
          $('#reservation').daterangepicker();
          //Date range picker with time picker
          $('#reservationtime').daterangepicker({timePicker: true, timePickerIncrement: 30, format: 'MM/DD/YYYY h:mm A'});
          //Date range as a button
          $('#daterange-btn').daterangepicker(
                  {
                    ranges: {
                      'Today': [moment(), moment()],
                      'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                      'Last 7 Days': [moment().subtract('days', 6), moment()],
                      'Last 30 Days': [moment().subtract('days', 29), moment()],
                      'This Month': [moment().startOf('month'), moment().endOf('month')],
                      'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                    },
                    startDate: moment().subtract('days', 29),
                    endDate: moment()
                  },
          function (start, end) {
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
          }
          );

          //iCheck for checkbox and radio inputs
          $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-blue',
            radioClass: 'iradio_minimal-blue'
          });
          //Red color scheme for iCheck
          $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
            checkboxClass: 'icheckbox_minimal-red',
            radioClass: 'iradio_minimal-red'
          });
          //Flat red color scheme for iCheck
          $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-blue'
          });

          //Colorpicker
          //$(".my-colorpicker1").colorpicker();
          //color picker with addon
          //$(".my-colorpicker2").colorpicker();

          //Timepicker
          //$(".timepicker").timepicker({showInputs: false});
        });
        </script>
        <?php endif; ?>
        
        <!-- Framework yOSON -->
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/libs/yoson.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/cnf/modules.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/cnf/validations.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/app/modules/admin.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/load.js"></script>
