
        <?php $admlte = $this->portal('admlte');?>
        <meta charset="UTF-8">
        <title>AdminLTE 2 | Dashboard</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- Bootstrap 3.3.2 -->
        <link href="<?php echo $admlte;?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- Font Awesome Icons -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        
        <?php if(TRUE): // is dashboard?>
        <!-- Morris chart -->
        <link href="<?php echo $admlte;?>/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
        <!-- jvectormap -->
        <link href="<?php echo $admlte;?>/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <!-- Daterange picker -->
        <link href="<?php echo $admlte;?>/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
        
        <?php if(TRUE): // is Cita form?>
        <!-- iCheck for checkboxes and radio inputs -->
        <link href="<?php echo $this->portal('admlte');?>/plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
        <?php endif;?>
    
        <!-- Theme style -->
        <link href="<?php echo $admlte;?>/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
        <link href="<?php echo $admlte;?>/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        
        <link href="<?php echo $this->portal('baseurl');?>/css/admin.css" rel="stylesheet" type="text/css" />
        
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <!-- Js log library -->
        <script src='<?php echo $this->portal('baseurl')?>/vendor/consolelog/consolelog.js'></script>
        <?php echo $this->headScript()->setIndent(8); //Solo carga script inline de variable Global ?>
