<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'JavaScript\Event\Listener'     => __DIR__ .'/src/JavaScript/Event/Listener.php',
  'JavaScript\Service\StoreScript'=> __DIR__ .'/src/JavaScript/Service/StoreScript.php',
  'JavaScript\Module'             => __DIR__ .'/Module.php',
);