
            <div id="footer-wrapper">
                <h4>Siéntase seguro:</h4>
                <p class="footer-texto">Para ofrecerle un mejor servicio estamos afiliados a las más importantes compañía de Seguros en el Perú, EEUU y Canadá.</p>
                <div class="imagen-centrada"><img src="img/convenios.gif" alt="convenios centro médico OSI" width="650" height="60" /></div>
                <div id="footer-wrapper-datos">
                    <div id="footer-direccion">
                        <h4>Visítanos en nuestras sedes:</h4>
                        <p class="footer-texto">
                            <strong>Miraflores:</strong> Calle Gonzales Prada 385. Alt. 50 de Paseo de la República<br /><br />
                            <strong>Surco - Chacarilla:</strong> Av. Del Pinar 198. Alt. 4 de Av. Primavera<br /><br />
                            <strong>Surco - El Trigal:</strong> Calle Los Antares 320. Torre "B". Oficina 202<br />
                            <br />
                            <strong>Los Olivos:</strong> Av. José Santos Chocano 1010 Alt. 5 de Carlos Izaguirre
                        </p><br />
                    </div>
                    <div id="footer-form">
                        <h4>Horario de Atención:</h4>
                        <p class="footer-texto">Lun a Vie de 8:00am - 10:00pm / Sab de 8:00am - 12:00m</p><br/>
                        <h4>Llámanos</h4>
                        <p class="footer-texto">01 739 0888<br/><br/>01 446 3693</p><br/>
                    </div>
                    <div class="limpiar"></div>
                </div>
                <div class="div-centrado">
                    <p class="footer-copyright">© Lima - Perú 2012. Organización de Salud Intercontinental. Todos los Derechos Reservados</p>
                </div> 
            </div>
