            <div id="logo"><a href="#" target="_self"><img src="img/logo.png" width="300" height="85" alt="Centro Médico OSI" /></a></div>
            <div id="facebook"><a href="http://www.facebook.com/centromedicoosi" target="_blank"><img src="img/facebook.jpg" width="100" height="25" alt="Facebook Centro Médico OSI" /></a></div>
            <div id="telefonos"><a href="#"><img src="img/telefonos.jpg" width="180" height="75" alt="Teléfonos Centro Médico OSI" /></a></div>
            <div id="menu">
                <div class="menu-wrapper1">
                    <div class="menu-wrapper2">
                        <div class="nav-wrapper">
                            <div class="nav-left"></div>
                            <div class="nav">
                                <ul id="navigation">
                                    <li class="#">
                                        <a href="#" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Inicio</span>
                                            <span class="menu-right"></span>
                                        </a>
                                    </li>

                                    <li class="#">
                                        <a href="" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Nosotros</span>
                                            <span class="menu-right"></span>
                                        </a>
                                        <div class="sub">
                                            <ul>
                                                <li><a href="nosotros/quienes-somos.html" target="_self">Quienes somos</a></li>
                                                <li class="last"><a href="nosotros/mision-vision.html" target="_self">Misión y visión</a></li>
                                            </ul>
                                            <div class="btm-bg"></div>
                                        </div>
                                    </li>

                                    <li class="#">
                                        <a href="staff.html" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Staff Profesional</span>
                                            <span class="menu-right"></span>
                                        </a>
                                    </li>

                                    <li class="#">
                                        <a href="" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Especialidades</span>
                                            <span class="menu-right"></span>
                                        </a>
                                        <div class="sub">
                                            <ul>
                                                <li><a href="fisioterapia-peru/index.html" target="_self">Fisioterapia</a></li>
                                                <li><a href="especialidades/centro-quiropractico.html" target="_self">Quiropráctica</a></li>
                                                <li><a href="acupuntura-peru/index.html" target="_self">Acupuntura</a></li>
                                                <li><a href="ondas-de-choque/index.html" target="_self">Ondas de Choque</a></li>
                                                <li><a href="especialidades/neurocirugia/index.html" target="_self">Neurocirugía</a></li>
                                                <li><a href="especialidades/nutricion.html" target="_self">Nutrición</a></li>
                                                <li class="last"><a href="especialidades/patologias-comunes.html" target="_self">Patologías comunes</a></li>
                                            </ul>
                                            <div class="btm-bg"></div>
                                        </div>    
                                    </li>

                                    <li class="#">
                                        <a href="programas-especializados.html" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Programas</span>
                                            <span class="menu-right"></span>
                                        </a>
                                    </li>

                                    <li class="last">
                                        <a href="contactenos.html" target="_self">
                                            <span class="menu-left"></span>
                                            <span class="menu-mid">Contáctenos</span>
                                            <span class="menu-right"></span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <div class="nav-right"></div>
                        </div>
                    </div>
                </div>
            </div>