
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

        <meta name="description" content="Con más de 12 años de trayectoria institucional y más de 10,000 pacientes atendidos, OSI es una de las instituciones más importantes de Fisioterapia, Quiropráctica y Acupuntura en el Perú. Convenios con Pacifico EPS, Rímac EPS, La Positiva, Mapfre. Centro Medico OSI" />
        <meta name="keywords" content="Acupuntura Peru, Quiropractico Peru, Fisioterapia Peru,  terapia fisica Peru, acupuntura en lima, acupuntura lima, dolor muscular, dolor articular, tratamiento stress, tratamiento artrosis, tratamiento artritis, tratamiento insomnio, tratamiento asma, tratamiento hipertensión, tratamiento parálisis facial, hernia del núcleo pulposo, hernia lumbar, Tratamiento Parálisis Facial" /> 

        <meta name="author" content="Centro Medico Especializado OSI" />  
        <meta name="copyright" content="www.centromedicoosi.com" />
        <meta name="document-distribution" content="Global" />
        <meta name="title" content="Centro Médico Especializado OSI - Fisioterapia, Quiropractico, Acupuntura y Nutrición" />  
        <title>Centro Médico Especializado OSI - Fisioterapia, Quiropractico, Acupuntura y Nutrición</title>

        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <link href="css/diagramacion.css" rel="stylesheet" type="text/css" />
        <link href="css/menu.css" rel="stylesheet" type="text/css" />
        <link href="js/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css" media="screen" />

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
        <script type="text/javascript" src="js/fancybox/jquery.fancybox.pack.js"></script>
        <script type="text/javascript" src="js/coin-slider.min.js"></script>
        
        <?php if(!$this->portal('islocal')):?>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-20880381-1']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
        <?php endif; ?>