
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p>Hemos desarrollado las mejores
                                    habilidades y técnicas fisioterapeúticas
                                    para lograr la recuperación de
                                    nuestros pacientes. </p>
                            </div>
                        </div> 
                        <div id="img" class="desaparecer"><img style="margin-left:15px;" src="images/doctora.png" width="246" height="422" alt="Fisioterapeutas en Lima" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p>
                            </div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo-int">
                            <h1>ESPECIALIDADES</h1></div>
                        <div id="red-social">            
                            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=2" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=2" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=2" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=2" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div class="texto-int"><p>El Centro Médico Especializado OSI, tiene más de 15 años de trayectoria institucional y la experiencia de haber atendido a más de 15,000 pacientes con excelentes resultados. Como centro especializado en Fisioterapia y Rehabilitación hemos desarrollado las mejores habilidades y técnicas fisioterapéuticas para lograr la recuperación de nuestros pacientes. </p>
                        </div> 
                        <div id="subtitulo"><h2>Contamos con especialistas en:
                            </h2></div>
                        <a href="especialidad-traumatologica"><div class="especialidad desaparecer"><h2>FISIOTERAPIA Y REHABILITACIÓN <br /> TRAUMATOLÓGICA</h2></div></a>
                        <div style="height:64px;margin-top:5px;" class="especialidad-text"><p>Para el tratamiento de las <span style="color:#7BAC39;" ><strong>lesiones traumáticas y ortopédicas </strong></span>(fracturas, tendinitis, desgarro muscular, entre otros).</p></div>

                        <a href="especialidad-neurologica"><div class="especialidad2 desaparecer"><h2>FISIOTERAPIA Y REHABILITACIÓN <br /> NEUROLÓGICA</h2></div></a>
                        <div class="especialidad-text"><p>Para el tratamiento de <span style="color:#7BAC39;" ><strong>Parálisis facial</strong></span>, nervio periféricos, Post ACV.</p></div>

                        <a href="especialidad-reumatologica"><div class="especialidad desaparecer"><h2>FISIOTERAPIA Y REHABILITACIÓN <br /> REUMATOLÓGICA</h2></div></a>
                        <div class="especialidad-text"><p>Para el tratamiento de <span style="color:#7BAC39;"><strong>artritis reumatoide</strong></span>, dolores crónicos, entre otros. </p></div>

                        <div class="especialidad2 desaparecer"><h2  style="margin-top:13px;" >FISIOTERAPIA DEPORTIVA</h2></div>
                        <div class="especialidad-text"><p>Especialistas en tratamientos para <span style="color:#7BAC39;" ><strong>lesiones deportivas</strong></span> y la recuperación de deportistas de alto rendimiento</p></div>

                        <a href="especialidad-salud-ocupacional"><div class="especialidad desaparecer"><h2 style="margin-top:13px;" >TERAPIA OCUPACIONAL</h2></div></a>
                        <div class="especialidad3-text especialidad-text"><p>Enfocados en la recuperación funcional de nuestros pacientes para que puedan retomar sus actividades de la vida diaria y el trabajo.</p></div>

                        <div class="texto-int"><p style="margin-top:15px;" ><span style="color:#7BAC39;" ><strong>Somos la red más grande de de especialistas en fisioterapi</strong>a</span> conformado por un Staff completo de médicos especialistas en fisioterapia y Rehabilitación; y fisioterapeutas completamente dedicados a la recuperación de nuestros pacientes.</p>
                            <p style="margin-top:10px;" >Contamos con los mejores equipos de Rehabilitación como el Láser, equipo crioterapia, Ultrasonido, TENS, Ondas Rusas, Magneto, Ondas de Choque, entre otros que nos permiten trabajar de forma integral con nuestros pacientes para una total recuperación.</p>
                            <p style="margin-top:10px;" >Si usted cree que necesita fisioterapia; no lo dude, llámenos. En OSI usted encontrará un equipo de profesionales dedicados a ofrecerle el mejor tratamiento. Algunas de las dolencias y patologías que tratamos son:</p>
                        </div> 
                        <div id="lista-especialidad">
                            <div style="margin-left:22px;" class="listita">
                                <ul>
                                    <li><a href="fisioterapia-para-artritis-reumatoidea">Artritis y Artrosis</a></li>
                                    <li><a href="fisioterapia-para-tendinitis">Tendinitis</a></li>
                                    <li><a href="fisioterapia-para-dolor-de-espalda">Dolor de Espalda</a></li>
                                </ul>
                            </div>
                            <div class="listita">
                                <ul>
                                    <li><a href="fisioterapia-para-fibromialgia">Fibromialgia</a></li>
                                    <li><a href="fisioterapia-para-acv-paralisis-facial">ACV y Parálisis Facial</a></li>
                                    <li><a href="fisioterapia-para-lesiones-deportivas">Lesiones Deportivas</a></li>
                                </ul>
                            </div>
                            <div class="listita">
                                <ul>
                                    <li><a href="fisioterapia-para-escoliosis">Escoliosis</a></li>
                                    <li><a href="fisioterapia-para-dolor-de-rodilla">Esguince</a></li>
                                    <li><a href="fisioterapia-para-lesion-articular">Desgarros Musculares y más</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>