
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p>Ayudamos a nuestros pacientes a 
                                    mejorar o restaurar la movilidad 
                                    que necesita para seguir 
                                    adelante<br /> con su vida
                                </p></div>
                        </div> 
                        <div style="margin-left:-15px;" id="img" class="desaparecer"><img src="images/f.neurologica.png" width="343" height="414" alt="Fisioterapia y Neurologia" longdesc="en algunos casos neurológicos, la recuperación podría ser poco a poco." /></div>



                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>

                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>

                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ESPECIALIDADES</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=4" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=4" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=4" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=4" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA NEUROLÓGICA</h1></div>
                        <div id="sub-especialidad"><h2><strong>RECUPERE FUERZA Y MOVILIDAD</strong></h2></div>

                        <div class="texto-int">
                            <p><span class="resaltado"><strong>En OSI contamos con especialistas con amplia experiencia en fisioterapia neurológica, área encargada de la evaluación y tratamiento de personas con problemas de movimiento causados por una enfermedad o lesión del sistema nervioso.</strong></span>  Nuestros fisioterapeutas pueden ayudarle a mejorar o restaurar la movilidad que necesita para seguir adelante con su vida.
                            </p>
                            <p style="margin-top:10px;" >Si  usted está buscando una alternativa a la cirugía y a los medicamentos, debería considerar el tratamiento de fisioterapia neurológica;  estudios científicos de Estados Unidos y Europa han corroborado su efectividad. 
                            </p>
                            <p style="margin-top:10px;" >Previo a la atención, un fisioterapeuta en OSI le examinará y desarrollara un plan de cuidado usando una variedad de técnicas que le ayuden a moverse mejor, recuperar el rango articular, restaurar su fuerza y prevenir la discapacidad asociada a una variedad de condiciones neurológicas.

                            </p>
                            <p style="margin-top:10px;" >Combinando la ciencia y la práctica, un especialista le enseñará cómo prevenir o manejar su problema de salud; delineando los objetivos del tratamiento y motivándolo a seguir para que pueda restablecer sus funciones de manera óptima. Tenga paciencia, en algunos casos neurológicos, la recuperación podría ser poco a poco.
                            </p>
                        </div> 

                        <div id="subtitulo"><h2>¿Cómo un especialista en fisioterapia puede ayudarme?
                            </h2></div>
                        <div id="menu-interno">
                            <ul>
                                <li><a class="activo" href="#">PREVENCIÓN</a></li>
                                <li><a href="#">FISIOTERAPIA NEUROLÓGICA</a></li>
                                <li><a href="#">INVESTIGACIÓN</a></li>
                            </ul>
                        </div>

                        <div style="display:block;" class="text-interno">
                            <p>Algunos factores de riesgo, como los antecedentes familiares, la edad, el género, la raza (las tasas de mortalidad de accidente cerebrovascular son más altos para los afroamericanos, incluso a edades más tempranas) no se pueden cambiar. Sin embargo, hay muchos que se pueden controlar, como la presión arterial alta, el tabaquismo, el colesterol alto, diabetes, enfermedad de la arteria carótida, la obesidad y la inactividad física.
                            </p>
                            <p>Como expertos en el diseño de planes de ejercicios adaptados para personas con una variedad de condiciones médicas, <span class="resaltado"><strong>nuestros especialistas en fisioterapia pueden ayudarle a reducir los factores de riesgo y revertir sus efectos mediante la creación de programas de ejercicios diseñados especialmente para usted.</strong></span></p>
                        </div>
                        <div style="display:none;" class="text-interno">
                            <p>La recuperación de un derrame cerebral depende de su tamaño y ubicación, la rapidez con la que el paciente recibe la atención y, en algunos casos, otras condiciones de salud pre - existentes. <span class="resaltado"><strong>La Fisioterapia y rehabilitación debe comenzar cuanto antes después del derrame cerebral, y los fisioterapeutas son una parte importante del equipo de recuperación.</strong></span>
                            </p>

                        </div>
                        <div style="display:none;" class="text-interno">
                            <p>Gran parte de la investigación actual en el campo de la rehabilitación de los accidentes cerebro vasculares y la recuperación está siendo liderada por especialistas en fisioterapia.<span class="resaltado"><strong>Gracias a sus investigaciones se han descubierto tratamientos innovadores para problemas de movilidad relacionados con el accidente cerebro vascular.</strong></span> 
                            </p>
                            <p>En el Centro Médico Especializado OSI, trabajamos junto a un equipo de médicos especialistas y fisioterapeutas comprometidos con la recuperación de todos nuestros pacientes. Contamos con un tratamiento multidisciplinario que combina las mejores prácticas de la fisioterapia, quiropráctica y acupuntura.</p>
                        </div>
                        <div id="consulte2">
                            <p>Si usted sufre de <span class="color-celeste">pérdida de movilidad a causa de una lesión del nervio u otra dolencia</span>, no lo dude; llámenos, consulte con nuestros especialistas</p>
                        </div>
                    </div>
                </div>