
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p>Hemos diseñado ejercicios de 
                                    estiramiento y fortalecimiento que 
                                    le ayudaran a sobrellevar <br /> la 
                                    enfermedad
                                </p></div>
                        </div> 
                        <div id="img" class="desaparecer"><img src="images/f.reumatologica.png" width="327" height="416" alt="Fisioterapia y Reumatologia" longdesc="Probablemente, usted puede experimentar una pérdida de movimiento en las articulaciones y como resultado puede tener dificultad para llevar a cabo sus actividades diarias normales. " /></div>



                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>

                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>

                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ESPECIALIDADES</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=5" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=5" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=5" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=5" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA REUMATOLÓGICA</h1></div>
                        <div id="sub-especialidad"><h2><strong>ELIMINE EL DOLOR. RECUPERE MOVILIDAD Y FUERZA.</strong></h2></div>

                        <div class="texto-int"><p><span class="resaltado"><strong>En el Centro Médico Especializado OSI, contamos con un equipo multidisciplinario de especialistas para el manejo de personas que sufren de dolencias y enfermedades reumáticas. </strong></span>
                            </p>
                            <p style="margin-top:10px;" >Nuestro equipo trabajará en estrecha colaboración con usted para asegurarse de que se sienta apoyado y tenga el mejor tratamiento posible.<span class="resaltado"><strong> Un fisioterapeuta tiene un papel clave a lo largo del curso de la enfermedad.</strong></span> El alcance de su participación puede variar durante todo ese tiempo dependiendo de sus necesidades; sin embargo siempre estará al tanto de su recuperación
                            </p>
                            <p style="margin-top:10px;" >A menudo los pacientes vienen derivados a fisioterapia poco después del diagnostico de la enfermedad reumática; en esta etapa podemos darles información y consejos para saber qué esperar y cómo manejar sus síntomas. 

                            </p>
                            <p style="margin-top:10px;" >Las personas que sufren de enfermedades reumáticas a menudo encuentran sus articulaciones más rígidas y los músculos más débiles. Probablemente, usted puede experimentar una pérdida de movimiento en las articulaciones y como resultado puede tener dificultad para llevar a cabo sus actividades diarias normales. Pensando en usted, hemos diseñado ejercicios de estiramiento y fortalecimiento que le enseñaremos durante las terapias para ayudarle a sobrellevar la enfermedad.
                            </p>
                        </div> 


                        <div style="margin-top:15px;" id="subtitulo"><h2>Los diagnósticos más frecuentes que hemos visto son:</h2></div>

                        <div id="lista-especialidad">
                            <div style="margin-left:22px;" class="listita">
                                <ul>
                                    <li>Artritis psoriásica</li>
                                    <li>Artritis reactiva</li>
                                    <li>Artritis Reumatoide</li>
                                    <li>Fatiga Crónica</li>
                                </ul>
                            </div>
                            <div class="listita">
                                <ul>
                                    <li>Fibromialgia</li>
                                    <li>Gota</li>
                                    <li>La artritis inflamatoria</li>
                                    <li>La espondilitis anquilosante</li>
                                </ul>
                            </div>
                            <div class="listita">
                                <ul>
                                    <li>Osteoartritis</li>
                                    <li>Polimialgia reumática</li>
                                    <li>Síndrome de Hiperlaxitud</li>
                                    <li>Trastornos musculo esqueléticos con enfermedad subyacente Reumatología
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div id="consulte3">
                            <p>Si usted sufre de <span class="color-celeste">dolores reumáticos o de un dolor crónico,</span> no lo dude; consulte con nuestros <span class="color-celeste">especialistas que gustosamente lo pueden atender.</span></p>
                        </div>

                    </div>
                </div>