
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p> Contamos con especialistas<br /> en 
                                    terapia ocupacional 
                                    altamente <br /> capacitados que combinan
                                    las mejores<br /> prácticas de fisioterapia

                                </p></div>
                        </div> 
                        <div id="img" class="desaparecer"><img src="images/salud-ocupacional.png" width="333" height="416" alt="Fisioterapia y Salud Ocupacional" longdesc="está enfocada en promover la recuperación de toda persona que padezca de algún tipo de dificultad motora o psíquica a raíz de alguna patología o enfermedad" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ESPECIALIDADES</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=6" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=6" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=6" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=6" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA EN SALUD OCUPACIONAL</h1></div>
                        <div id="sub-especialidad"><h2><strong>RECUPERAMOS TU MÁXIMO POTENCIAL</strong></h2></div>

                        <div class="texto-int"><p>La terapia ocupacional está enfocada en promover la recuperación de toda persona que padezca de algún tipo de dificultad motora o psíquica a raíz de alguna patología o enfermedad que le impida realizar sus actividades con normalidad. 

                            </p>
                            <p style="margin-top:10px;" ><span class="resaltado"><strong>En el Centro Médico Especializado OSI, contamos con especialistas en terapia ocupacional</strong></span> altamente capacitados que combinan las mejores prácticas de la fisioterapia, la acupuntura y quiropráctica para lograr una efectiva y pronta atención. Durante las sesiones, desarrollamos programas individuales que abarcan de forma integral la recuperación de los déficits motores, sensoriales y cognitivos del paciente. 
                            </p>

                        </div> 

                        <div id="subtitulo"><h2>Nuestros Programas Incluyen:
                            </h2></div>
                        <div id="menu-interno2">
                            <ul>
                                <li><a class="activo" href="#">TERAPIA OCUPACIONAL PARA ADULTOS</a></li>
                                <li><a href="#">TERAPIA OCUPACIONAL PARA NIÑOS</a></li>

                            </ul>
                        </div>

                        <div style="display:block;" class="text-interno">
                            <p style="width:314px;" >Para la rehabilitación<span class="resaltado"><strong> Post ACV, lesiones en la columna</strong></span>, parálisis facial, traumatismos craneoencefálico, enfermedades reumáticas; entre otros. En OSI; contamos con médicos especialistas en Salud Ocupacional y fisioterapeutas dedicados. Contamos con <span><strong>experiencia en la atención de pacientes de SCTR de los principales clientes de Pacifico y Rímac Seguros </strong></span>en empresas como Antamina, Southern Perú, Yanacocha, Ripley, entre otros. </p>
                            <div class="foto-int"><img src="images/salud-ocupacional-adultos.jpg" width="293" height="151" alt="salud-ocupacional-adultos" longdesc="Para la rehabilitación Post ACV, lesiones en la columna, parálisis facial, traumatismos craneoencefálico, enfermedades reumáticas; entre otros. " /></div>
                        </div>

                        <div style="display:none;" class="text-interno">
                            <p style="width:314px;" >La terapia ocupacional para niños está especialmente <span><strong class="resaltado">diseñada para promover el desarrollo optimo de las funciones de niños que tengan dificultad para escribir, leer, vestirse, hablar, entre otros</strong>.</span> Antes de iniciar su terapia el especialista de OSI realizará una evaluación exhaustiva de las habilidades de su niño para desarrollar un plan de tratamiento que ayude a potenciar sus habilidades. 
                            </p>
                            <div class="foto-int"><img src="images/salud-ocupacional-ninos.jpg" width="293" height="151" alt="" longdesc="La terapia ocupacional para niños está especialmente diseñada para promover el desarrollo optimo de las funciones de niños que tengan dificultad para escribir, leer, vestirse, hablar, entre otros. Antes de iniciar su terapia el especialista de OSI realizará una evaluación exhaustiva de las habilidades de su niño para desarrollar un plan de tratamiento que ayude a potenciar sus habilidades. " /></div>
                        </div>
                        <div id="consulte">
                            <p style="margin-top:109px;" >Si usted ha <span class="color-celeste">sufrido de un ACV y requiere atención, llámenos,</span> nuestros especialistas gustosamente le pueden atender.</p>
                        </div>
                    </div>
                </div>