
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p>Creemos fervientemente que un<br /> 
                                    trabajo  en equipo entre el especialista<br />
                                    y el paciente es fundamental 
                                    para una pronta recuperación</p></div>
                        </div> 
                        <div style="margin-top:7px;" id="img"  class="desaparecer" ><img src="images/f-traumatologica2.png" width="327" height="381" alt="Fisioterapia y Traumatologia" longdesc="Las sesiones de fisioterapia traumatológica correctamente aplicadas pueden evitar una posible cirugía y promueven una recuperación más rápida en los casos de pacientes post operados." /></div>



                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p></div>
                        </div>

                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>

                    </div>
                    <div id="columna2">
                        <div id="titulo1"><p>ESPECIALIDADES</p></div>
                        <div id="red-social">            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=3" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=3" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=3" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=3" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div style="margin-top:5px;" id="titulo-int">
                            <h1>FISIOTERAPIA TRAUMATOLÓGICA</h1></div>
                        <div id="sub-especialidad"><h2><strong>ELIMINA TU DOLOR Y RECUPERA FUNCIONABILIDAD</strong></h2></div>

                        <div class="texto-int"><p>Es una de las especialidades más demandadas hoy en día por su eficacia para la rehabilitación de pacientes que sufren de dolor en las articulaciones, los músculos e inclusive tienen algún problema óseo estructural.</p>
                            <p style="margin-top:10px;" >Las sesiones de fisioterapia traumatológica correctamente aplicadas pueden evitar una posible cirugía y promueven una recuperación más rápida en los casos de pacientes post operados.
                            </p>
                            <p style="margin-top:10px;" ><span class="resaltado"><strong>En el Centro Médico Especializado OSI, creemos que el conocimiento y un claro entendimiento de las lesiones traumáticas y ortopédicas es esencial para una planificación correcta del tratamiento para nuestros pacientes.</strong></span> Durante sus sesiones, un fisioterapeuta le ayudará a entender su diagnostico y le guiará en el proceso de su recuperación. Creemos fervientemente que un trabajo en equipo entre el especialista y usted es fundamental para su pronta recuperación.
                            </p>
                            <p style="margin-top:10px;" ><span class="resaltado"><strong>Previo al tratamiento será evaluado para determinar su diagnostico y los síntomas que más le aquejan.</strong></span> Si tiene exámenes auxiliares como rayos X o resonancias magnéticas es importante que las lleve para que el médico pueda tener una apreciación más exacta de su caso. Si no las tiene y el médico no las indica, no se preocupe, probablemente el médico ha determinado que no son necesarios.
                            </p>
                        </div> 

                        <div id="subtitulo"><h2>Nuestros tratamientos de Fisioterapia traumatológica tienen los siguientes objetivos:
                            </h2></div>
                        <div style="width:628px;" id="lista-especialidad">
                            <div style="margin-left:22px;width:628px;" class="listita">
                                <ul style="width:628px;" >
                                    <li style="width:550px;" >Eliminar el dolor. Enseñar estrategias de manejo del dolor.</li>
                                    <li style="width:550px;margin-top:2px;" >Maximizar su seguridad y autonomía funcional.</li>
                                    <li style="width:590px;margin-top:2px" >Maximizar la participación de los pacientes en el desarrollo de sus actividades como el colegio, el trabajo y las actividades recreativas</li>
                                    <li style="width:590px;margin-top:2px;" >Minimizar el impacto de la discapacidad como consecuencia de una lesión traumática en las actividades diarias de nuestros pacientes.</li>
                                </ul>
                            </div>
                        </div>
                        <div style="margin-bottom:20px;" class="texto-int"><p style="margin-top:15px;" ><span class="resaltado"><strong>En el Centro Médico Especializado OSI, trabajamos junto a un equipo de médicos especialistas y fisioterapeutas comprometidos con la recuperación de todos nuestros pacientes.</strong></span> Contamos con un tratamiento multidisciplinario que combina las mejores prácticas de la fisioterapia traumatológica, quiropráctica y acupuntura.</p>
                            <p style="margin-top:10px;" > Si usted sufre de dolor a causa de una lesión muscular o un esguince, tendinitis, una fractura u otra dolencia a causa de un trauma, no lo dude; llámenos, consulte con nuestros especialistas. </p>

                        </div> 

                        <div id="consulte">
                            <p>Si usted sufre de dolor a causa de una <span class="color-celeste">lesión muscular o un esguince, tendinitis, una fractura </span></span>u otra dolencia a causa de un trauma, no lo dude; llámenos, consulte con nuestros especialistas. </p>
                        </div> 


                    </div>
                </div>