<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>AdminLTE 2 | Log in</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- Bootstrap 3.3.2 -->
        <link href="<?php echo $this->portal('admlte');?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- Font Awesome Icons -->
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="<?php echo $this->portal('admlte');?>/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <!-- iCheck -->
        <link href="<?php echo $this->portal('admlte');?>/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
        <!-- Js log library -->
        <script src='<?php echo $this->portal('baseurl')?>/vendor/consolelog/consolelog.js'></script>
        <?php echo $this->headScript()->setIndent(8); //Solo carga script inline de variable Global ?>
    </head>
    <body class="login-page">
        <div class="login-box">
            <div class="login-logo">
                <a href="<?php echo $this->portal('baseurl');?>">
                    <img src="<?php echo $this->portal('baseurl');?>/img/logo.png" />
                </a>
            </div><!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg">Inicie sesion de usuario administrador.</p>
                <form id="admLoginForm" action="/portal/usuario/login?adm" method="post">
                    <div class="form-group has-feedback">
                        <select name="tipodoc" id="usutipodoc" class="form-control">
                            <option value="1">Dni</option>
                            <option value="2">Pasaporte</option>
                        </select>
                        <span class="glyphicon glyphicon-folder-open form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input id="usutipodoc" name="nrodoc" type="text" class="form-control" placeholder="Numero de documento" required />
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input id="usupass" name="pass" type="password" class="form-control" placeholder="Contrase&ntilde;a" required />
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">    
                            <div class="checkbox icheck">
                                <label><!--input type="checkbox"> Remember Me--></label>
                            </div>                        
                        </div><!-- /.col -->
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Login</button>
                        </div><!-- /.col -->
                    </div>
                </form>
                <!--div class="social-auth-links text-center">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
                    <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
                </div>
                <!--
                <a href="#">I forgot my password</a><br>
                <a href="register.html" class="text-center">Register a new membership</a>
                -->
            </div><!-- /.login-box-body -->
        </div><!-- /.login-box -->

        <!-- jQuery 2.1.3 -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <!-- Bootstrap 3.3.2 JS -->
        <script src="<?php echo $this->portal('admlte');?>/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!-- iCheck -->
        <script src="<?php echo $this->portal('admlte');?>/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <script>
            $(function () {
                $('input').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
        
        <!-- Framework yOSON -->
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/libs/yoson.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/cnf/modules.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/cnf/validations.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/app/modules/admin.js"></script>
        <script src="<?php echo $this->portal('baseurl')?>/js/yoson/load.js"></script>
    </body>
</html>