
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube2">
                            <div class="content">
                                <div style="margin-top:19px;width:250px;margin-left:0px;" class="tex-nube">
                                    <div class="text-contactanos">
                                        <div class="icon-cita"><img src="images/taco.png" width="13" height="17" /></div>
                                        <div class="texto-contact"><p id="mapDirec" style="font-size:15px;">Calle Gonzáles Prada 385 Alt.50 Paseo de la República.</p></div>
                                    </div> 
                                    <div class="text-contactanos" style="margin-top:6px;" >
                                        <div class="icon-cita"><img src="images/telf-cita.png" width="13" height="17" alt="" /></div>
                                        <div class="texto-contact"><p style="font-size:15px;" >739 0888</p></div>
                                    </div>  
                                </div>
                            </div>
                        </div>
                        <div id="img"><img src="images/contactenos.png" width="324" height="447"  alt="Fisioterapia en Lima"/></div>
                    </div>
                    <div id="columna2" style="height:650px;">
                        <div id="titulo-int"><h1>CONTÁCTENOS</h1></div>
                        <div id="menu-interno3">
                            <ul id="mapas">
                                <li><a id="mapMrflrs" class="activo" href="#">MIRAFLORES</a></li>
                                <li><a id="mapSurco" href="#">SURCO-CHACARILLA</a></li>
                                <li><a id="mapOlivos" href="#">LOS OLIVOS</a></li>
                                <!--<li><a href="#">LIMA</a></li>-->
                            </ul>
                        </div>
                        <style> .mapa-contanto{position:absolute;top:98px;} </style>
                        <div class="mapa-contanto">
                            <iframe id="ifrmMapa" name="ifrmMapa" src="/mapa" height="100%" width="100%" scrolling="no" frameborder="0"></iframe>
                        </div>
                        <!--div class="mapa-contanto" style="display:none;"><iframe src="mapa-surco.html" height="100%" width="100%" scrolling="no" frameborder="0"></iframe></div>
                        <div class="mapa-contanto" style="display:none;"><iframe src="mapa-los-olivos.html" height="100%" width="100%" scrolling="no" frameborder="0"></iframe></div>
                        <div class="mapa-contanto" style="display:none;"><iframe src="mapa-lima.html" height="100%" width="100%" scrolling="no" frameborder="0"></iframe></div-->
                    </div>
                </div>