
            <div id="banner">
                <div id="coin-slider">
                    <img src="img/banner/ba1.jpg" title="" />
                    <img src="img/banner/ba2.jpg" title="" />
                    <img src="img/banner/ba3.jpg" title="" />
                    <img src="img/banner/ba4.jpg" title="" />
                    <img src="img/banner/ba5.jpg" title="" />
                    <img src="img/banner/ba6.jpg" title="" />
                    <img src="img/banner/ba7.jpg" title="" />
                </div> 
            </div>
            <!-- Fin del Banner -->
            <div id="especialidades" class="cf">
                <ul class="ul-especialidad">
                    <li class="separador">
                        <div class="especialidad-titular"><h1><a href="especialidades/fisioterapia.html">Fisioterapia</a></h1></div>
                        <div class="especialidad-contenido"> <a href="especialidades/fisioterapia.html"><img src="img/fisioterapia.jpg" width="290" height="150" alt="Fisioterapia" /></a>
                            <p class="especialidad-detalle">Con más de 12 años de trayectoria institucional y la más alta tecnología de vanguardia ...</p>
                            <p class="mas"><a href="#">Ver más &gt;&gt;</a></p>
                        </div>
                    </li>

                    <li class="separador">
                        <div class="especialidad-titular"><h1><a href="especialidades/centro-quiropractico.html">Quiropraxia computarizada</a></h1></div>
                        <div class="especialidad-contenido"> <a href="especialidades/centro-quiropractico.html"><img src="img/quiropraxia.jpg" width="290" height="150" alt="Quiropractico" /></a>
                            <p class="especialidad-detalle">Nuestro sistema quiropráctico permite que los ajustes se realicen de la forma más segura, precisa y sin dolor...</p>
                            <p class="mas"><a href="especialidades/centro-quiropractico.html">Ver más &gt;&gt;</a></p>
                        </div>
                    </li>

                    <li>
                        <div class="especialidad-titular"><h1><a href="acupuntura-peru/index.html">Acupuntura y homeopatía</a></h1></div>
                        <div class="especialidad-contenido"> <a href="acupuntura-peru/index.html"><img src="img/acupuntura.jpg" width="290" height="150" alt="Acupuntura" /></a>
                            <p class="especialidad-detalle">El Centro Especializado OSI es especialista en Acupuntura y Homeopatía. Trata complejas ...</p>
                            <p class="mas"><a href="acupuntura-peru/index.html">Ver más &gt;&gt;</a></p>
                        </div>
                    </li>

                    <li class="separador">
                        <div class="especialidad-titular"><h1><a href="especialidades/neurocirugia/index.html">Neurocirugía</a></h1></div>
                        <div class="especialidad-contenido"> <a href="especialidades/neurocirugia/index.html"><img src="img/medicina-general.jpg" width="290" height="150" alt="Fisioterapia" /></a>
                            <p class="especialidad-detalle">En alianza con el Instituto de Neurociencias de Lima contamos con un equipo de destacados médicos ...</p>
                            <p class="mas"><a href="especialidades/neurocirugia/index.html">Ver más &gt;&gt;</a></p>
                        </div>
                    </li>

                    <li class="separador">
                        <div class="especialidad-titular"><h1><a href="especialidades/nutricion.html">Nutrición</a></h1></div>
                        <div class="especialidad-contenido"> <a href="especialidades/nutricion.html"><img src="img/nutricion.jpg" width="290" height="150" alt="Acupuntura" /></a>
                            <p class="especialidad-detalle">Nuestro departamento de Nutrición realiza una evaluación personalizada en base a la edad, peso, talla y ...</p>
                            <p class="mas"><a href="especialidades/nutricion.html">Ver más &gt;&gt;</a></p>
                        </div>
                    </li>

                    <li>
                        <div class="anuncio">
                            <a href="programas-especializados.html"><img src="img/programa.jpg" width="290" height="221" alt="Programa Quiropractico" /></a>
                        </div>
                    </li>

                </ul>
            </div>
