                    <div id="content-content">
                        <div id="columna1">
                            <div id="nube">
                                <div id="tex-nube"><p style="margin-top:8px;" >Ofrecemos el mejor cuidado y
                                        una excelente atención médica 
                                        a <br />nuestros pacientes


                                    </p></div>
                            </div> 
                            <div id="img"><img src="images/porque-osi.png" width="249" height="414" /></div>
                            <div id="seguro-int">
                                <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                                <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                                <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                        de Seguros en el Perú, EEUU y Canadá.</p></div>
                            </div>
                            <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                        </div>
                        <div id="columna2">

                            <div id="titulo-int">
                                <h1>POR QUÉ ELEGIR OSI</h1></div>
                            <div id="red-social">            <div id="red-social2">
                                    <div class="face"><a href="redes_servicios.php?id=1" title="Facebook"></a></div>
                                    <div class="twit"><a href="redes_servicios.php?id=1" title="Twitter"></a></div>
                                    <div class="mensaje"><a href="redes_servicios.php?id=1" title="Envía a un amigo"></a></div>
                                    <div class="like"><a href="redes_servicios.php?id=1" title="Me gusta"></a></div>
                                </div>
                            </div>

                            <div style="margin-top:10px;" class="subtitulo"><h2>Equipo de Médicos Especialistas y Fisioterapeutas a dedicación exclusiva
                                </h2></div>


                            <div class="texto-int">
                                <p>En OSI contamos con médicos especialistas en Medicina Física y Rehabilitación; y fisioterapeutas a dedicación exclusiva lo que nos permite ofrecerle un tratamiento personalizado. Además, el trabajo en equipo nos ha permitido desarrollar protocolos de atención para lograr mejores resultados. 
                                </p>
                            </div>



                            <div class="subtitulo"><h2>Tratamiento Multidisciplinario: Fisioterapia, Quiropráctica y Acupuntura
                                </h2></div>

                            <div class="texto-int">
                                <p>Durante sus sesiones, combinamos las mejores prácticas de la Fisioterapia, Quiropráctica y Acupuntura para abordar su dolencia de forma multidisciplinaria; tratamos su dolencia desde un punto de vista muscular y articular; del sistema nervioso y sistema esquelético estructural.  
                                </p>
                            </div>

                            <div class="subtitulo"><h2>Atención Personalizada más allá de la consulta y terapia. 
                                </h2></div>

                            <div class="texto-int">
                                <p>Después de la consulta o de la terapia puede que tengas alguna duda o consulta para el médico o tu fisioterapeuta; por ello tienes todas las facilidades para ponerte en contacto vía email o teléfono con tu especialista tratante las veces que creas necesarias. 
                                </p>
                            </div>

                            <div class="subtitulo"><h2>Consultorios Equipados con la mejor tecnología
                                </h2></div>

                            <div class="texto-int">
                                <p>En el Centro Médico Especializado OSI contamos con la mejor tecnología en equipos de fisioterapia y rehabilitación. Contamos con los mejores equipos de Estados Unidos, Europa y Asia. 
                                </p>
                            </div>
                        </div>
                    </div>