                    <div id="content-content">

                        <div style="width:980px;" id="columna2">
                            <div id="trabaje-texto"><p>En OSI cada día es un desafío para nuestro equipo</p></div>

                            <div id="trabaje-texto2"><p>Si quieres ser parte de un gran equipo y eres un profesional dedicado a la felicidad de tus pacientes, y estas comprometido con su recuperación, tenemos un lugar para ti.
                                    Envíanos tu C V para poder conocerte.</p></div>

                            <div style="margin-top:25px;margin-left:232px;margin-bottom:15px;" id="titulo-int">
                                <h1>TRABAJA CON NOSOTROS</h1></div>

                            <div style="margin-left:212px;" id="formulario">
                                <form id="form_contac" name="form_contac" action="trabaja_nosotros_envia.php" method="post" style="width:530px; float:left;margin-left:20px;height:20px;">

                                    <span id="sprytextfield2">
                                        <label for="nombre"></label>
                                        <input type="text" name="nombre" id="nombre" class="celda2" />
                                        <div class="asterisco">*</div>
                                    </span> <span id="sprytextfield3">
                                        <label for="apellidos"></label>
                                        <input type="text" name="apellido" id="apellido" class="celda2"/>
                                        <div class="asterisco">*</div>
                                    </span> <span id="sprytextfield4">
                                        <label for="distrito"></label>
                                        <input type="text" name="distrito" id="distrito" class="celda2"/>
                                        <div class="asterisco">*</div>
                                    </span> 
                                    <span id="sprytextfield5">
                                        <label for="e-mail"></label>
                                        <input type="text" name="email" id="email" class="celda2"/>
                                        <div class="asterisco">*</div>
                                    </span>
                                    <span id="sprytextfield6">
                                        <label for="confirma-email"></label>
                                        <input type="text" name="con_email" id="con_email" class="celda2"/>
                                        <div class="asterisco">*</div>
                                    </span>

                                    <span id="sprytextfield7">
                                        <label for="edad"></label>
                                        <input type="text" name="edad" id="edad" class="celda2"/>
                                        <div class="asterisco">*</div>
                                    </span>


                                    <span id="spryselect2">
                                        <label for="grado-academico"></label>
                                        <select name="grado-academico" id="grado-academico" class="celda4">
                                            <option selected="selected">Grado Académico:</option>

                                            <option value="Médico Especialista/Residente">Médico Especialista/Residente</option>
                                            <option value="Licenciado TM. Fisioterapia">Licenciado TM. Fisioterapia</option>
                                            <option value="Bachiller TM. Fisioterapia">Bachiller TM. Fisioterapia</option>
                                            <option value="Técnico en Fisioterapia">Técnico en Fisioterapia</option>
                                            <option value="otros">Otros Estudios</option>


                                        </select>
                                        <div class="asterisco">*</div>
                                    </span> 

                                    <span id="spryselect3">
                                        <label for="anos_experiencia"></label>
                                        <select name="anos_experiencia" id="anos_experiencia" class="celda4">
                                            <option selected="selected">Años de Experiencia:</option>
                                            <option value="1 - 2">1 - 2</option>
                                            <option value="3 - 5">3 - 5</option>
                                            <option value="6 - 10">6 - 10</option>
                                            <option value="más de 10 años">más de 10 años</option>
                                        </select>
                                        <div class="asterisco">*</div>
                                    </span>

                                    <div id="btn-confirmar"><img src="images/btn-adjunta.jpg" width="507" height="32" alt="btn-adjuntar" /></div> <div class="asterisco">*</div>
                                    <input type="file"  name="archivo" id="archivo" style="position: absolute;margin-top:183px;margin-left:-518px;width:500px;height:30px;cursor:pointer; opacity:0;" />
                                    <div id="texto_file"><p>Adjunte Un Archivo....</p></div>
                                    <span id="sprytextarea1">
                                        <label for="consulta"></label>
                                        <textarea name="consulta" cols="45" rows="5" class="celda5" id="consulta" style="height:110px;"></textarea>
                                        <div class="asterisco">*</div>
                                        <p style="width: 450px; margin: 0; padding: 0 0 0 3px; font-size: 12px;">* Campos obligatorios</p>
                                    </span>
                                    <input type="image" src="images/enviar-boton.png" width="67" height="25" alt="" style="float:right; margin: 0px 15px 20px 0;"/>
                                </form>

                            </div>   
                        </div>
                    </div>