
                                <div id="loginWarn" class="alert alert-warning alert-dismissible" role="alert" style="display:none;">
                                    <strong>Error ! </strong> Datos incorrectos.
                                </div>

                                <form id="formLogin" class="form-horizontal" action="/portal/usuario/login" role="form">
                                    <div class="form-group">
                                        <label for="inputEmail3" class="col-sm-5 control-label">Tipo documento</label>
                                        <div class="col-sm-7">
                                            <select class="form-control" id="usutipodoc" name="tipodoc">
                                                <option value="1">Dni</option>
                                                <option value="2">Pasaporte</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="inputEmail3" class="col-sm-5 control-label">Nro. documento</label>
                                        <div class="col-sm-7">
                                            <input type="text" value="" placeholder="Nro de documento" class="form-control" id="usunrodoc" name="nrodoc" required />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="inputEmail3" class="col-sm-5 control-label">Password</label>
                                        <div class="col-sm-7">
                                            <input type="password" value="" placeholder="Contrase&ntilde;a" class="form-control" id="usupass" name="pass" required />
                                        </div>
                                    </div>

                                    <center><div class="input-group">
                                        <button type="submit" class="btn btn-primary">Iniciar sesion</button>
                                    </div></center>
                                </form>
