                                            <?php $form = $this->formcita; ?>
                                            <div class="alert alert-warning" role="alert">
                                                <strong>Nota : </strong> Usted podra re-agendar una cita solo una vez y 6 horas antes de la misma. 
                                            </div>

                                            <div class="row show-grid">
                                                <div class="col-sm-6"><?php echo $this->formRow($form->get('idseguro'))?></div>
                                                <div class="col-xs-6"></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-sm-6"><?php echo $this->formLabel($form->get('frmsede'))?></div>
                                                <div class="col-xs-6"></div>
                                            </div>
                                            
                                            <div class="row show-grid">
                                                <div class="col-sm-6"><?php echo $this->formSelect($form->get('frmsede'))?></div>
                                                <div class="col-xs-6">
                                                    <button id="citaVerMapa" type="button" class="btn btn-link" disabled>Ver mapa</button>
                                                </div>
                                            </div>
                                            <div id="rowIfrmMapa" class="row show-grid" style="display:none">
                                                <div class="col-sm-12">
                                                    <?php $mca = $this->portal('mca');?>
                                                    <iframe width="100%" height="310" frameborder="0" scrolling="no" <?php if($mca['modu']=='portal'):?>src="/mapa"<?php endif;?> name="ifrmMapa" id="ifrmMapa"></iframe>
                                                </div>
                                            </div>
                                            
                                            <div class="row">
                                                <div class="col-sm-6"><?php echo $this->formLabel($form->get('idhorario'))?></div>
                                                <div class="col-xs-6"></div>
                                            </div>
                                            <div class="row show-grid">
                                                <div class="col-sm-6">
                                                    <select id="frmhorario" class="form-control" disabled>
                                                        <option value="0">- Elija horario</option><?php echo $this->days?>
                                                    </select>
                                                </div>
                                                <div class="col-xs-6">
                                                    <select id="frmespec" class="form-control" disabled>
                                                        <option>- Elija especialista</option>
                                                    </select>
                                                    <?php echo $this->formHidden($form->get('idhorario'))?>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <?php echo $this->formHidden($form->get('datehour'))?>
                                                <div id="citaHoras" class="col-sm-12"></div>
                                            </div>