
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube" class="desaparecer">
                            <div id="tex-nube"><p>Nuestro tratamiento<br /> multidisciplinario 
                                    combina las mejores prácticas de la 
                                    fisioterapia, acupuntura y 
                                    quiropráctica computarizada </p>
                            </div>
                        </div> 
                        <div id="img" class="desaparecer"><img src="images/doctor1.png" width="286" height="437" alt="Especialista en Fisioterapia" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p>
                            </div>
                        </div>
                        <div id="duda"><img src="images/duda.png" width="312" height="175" alt="osi" /></div>
                    </div>
                    <div id="columna2" class="desaparecer">
                        <div id="titulo-int"><h1>QUIÉNES SOMOS</h1></div>
                        <div id="red-social"> 
                            <div id="red-social2">
                                <div class="face"><a href="redes_servicios.php?id=1" title="Facebook"></a></div>
                                <div class="twit"><a href="redes_servicios.php?id=1" title="Twitter"></a></div>
                                <div class="mensaje"><a href="redes_servicios.php?id=1" title="Envía a un amigo"></a></div>
                                <div class="like"><a href="redes_servicios.php?id=1" title="Me gusta"></a></div>
                            </div>
                        </div>
                        <div class="texto-int">
                            <p>Somos la Red de Especialistas en Fisioterapia y Rehabilitación más grande del Perú. Como Centro Médico Especializado OSI contamos con cerca de <strong><span style="color:#7BAC39;">15 años de trayectoria institucional y la experiencia de haber atendido a más de 15,000 pacientes con excelentes resultados clínicos.</span></strong> </p>
                            <p>En OSI estamos convencidos en que ofrecer el mejor cuidado y una excelente atención medica a nuestros pacientes es el único camino hacia el éxito terapéutico. Gracias a ello, podemos contar con la confianza y el respaldo de las principales compañías de Seguro y EPS como Pacifico, Rímac, Mapfre y La Positiva para atender a sus principales clientes.</p>
                            <p style="margin-bottom:10px;"><strong><span style="color:#7BAC39;">Nuestra ventaja sobre otros tipos de procedimientos, es nuestro tratamiento multidisciplinario que combina las mejores prácticas de la fisioterapia, acupuntura y quiropráctica computarizada. </span></strong>Hemos diseñado un plan terapéutico para diversos tipos de dolencias y enfermedades personalizado basado en nuestra amplia experiencia.
                                Le invitamos a conocernos, estaremos gustosos de atenderle y comprometidos en ofrecerle el mejor tratamiento que esté en nuestras manos.
                            </p>
                        </div> 

                        <div class="separa-int"><img src="images/separa-int.png" width="628" height="1" alt="separa" /></div>
                        <div id="mision">
                            <div id="fondo-mision"><p>MISIÓN</p></div>
                            <div id="texto-mision"><p>Ofrecer a nuestros pacientes una excelente atención médica a través de un servicio de máximo nivel basado en integridad, experiencia y tecnología.</p></div>
                        </div>
                        <div id="vision">
                            <div id="fondo-vision"><p>VISIÓN</p></div>
                            <div id="texto-vision"><p>Ser la Red de Especialistas en Fisioterapia y Rehabilitación más grande en toda Latino América. Reconocidos mundialmente por ofrecer un tratamiento de alta calidad en base a un diagnostico preciso  y un tratamiento efectivo y oportuno.</p></div>
                        </div>

                        <div id="consulte">
                            <p>Si usted sufre de alguna enfermedad o dolor, no se preocupe, no está solo. <span class="color-celeste">Nuestros especialistas estan dispuestos a ayudarle</span> durante todo el tratamiento hasta su recuperación</p>
                        </div>

                    </div>
                </div>
