
                <div id="content-content">
                    <div id="columna1">
                        <div id="nube">
                            <div id="tex-nube">
                                <p>Contamos con los mejores <br />especialistas y los más avanzados <br />equipos médicos para combatir cualquier dolencia. </p>
                            </div>
                        </div>
                        <div id="img"><img src="images/staff.png" width="305" height="435" alt="Medico: Medico de Medicina Fisica y Rehabilitacion" /></div>
                        <div id="seguro-int">
                            <div id="titulo-seguro"><p>Contamos con el Respaldo de:</p></div>
                            <div id="all-seguros"><img src="images/seguros-int.png" width="316" height="186" alt="seguros" /></div>
                            <div id="texto-seguros"><p>Estamos afiliados a las más importantes compañías 
                                    de Seguros en el Perú, EEUU y Canadá.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div id="columna2">
                        <div id="titulo-int"><h1>NUESTROS ESPECIALISTAS</h1></div>
                        <div id="staff">
                            <div id="sub-especialidad" style="margin-top:15px;" ><h2 style="font-seze:16px;" ><strong>MEDICINA FÍSICA Y REHABILITACIÓN - ACUPUNTURA</strong></h2></div>
                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dr. Wingyen Mac</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:none;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle">
                                    <ul>
                                        <li>CMP 19658</li>
                                        <li>Director Médico General</li>
                                        <li>
                                            <span itemprop="title"> Médico con una extensa experiencia en Columna y Rehabilitación Trauma Neurológica</span>
                                        </li>
                                        <li>Medico Acupuntor.</li>
                                        <li>Univ. de Medicina Zhongshan R.P. China. 1983</li>
                                        <li>Postgrado en Acupuntura y Medicina Tradicional China, Guangzhou - China.</li>
                                        <li>Médico miembro de la Asociación de Medicina de Rehabilitación de Guangdong, RP. China.</li>
                                        <li>Univ. Nacional Mayor de San Marcos - Perú. 1986</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dra. Erika giraldo Vizcarra</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 38989 RNE 20436</li>
                                        <li>Director Médico</li>
                                        <li>
                                            <span itemprop="title">Médico especialista en Medicina Física y Rehabilitación</span>
                                        </li>
                                        <li>Médico de la Univ. Católica de Santa María</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Nacional Mayor de San Marcos.</li>
                                        <li>Diplomado en Salud Ocupacional en Univ. Nacional Mayor de San Marcos</li>
                                        <li>Ponente en diversos eventos científicos y realizado trabajos de investigación.</li>
                                        <li>Jefe del Servicio de Medicina Física y Rehabilitación del Hospital San Isidro Labrador</li>
                                        <li>Presidenta del Comité de Auditoría Médica del Hospital San Isidro Labrador</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dr. Oswaldo Rosales Galarza</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 9080 RNE 5692</li>
                                        <li>
                                            <span itemprop="title"> Médico especialista en Medicina Física y Rehabilitación</span>
                                        </li>
                                        <li>Médico de la Univ. Nacional Mayor de San Marcos</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Nacional Mayor de San Marcos</li>
                                        <li>30 años de experiencia profesional en Medicina Física y Rehabilitación.</li>
                                        <li>Ponente especializado en Hemiplejías, & Salud Ocupacional en diversos eventos científicos.</li>
                                        <li>Profesora de Medicina Física y Rehabilitación en la UNMSM, Univ. Federico Villareal y Univ. Cayetano Hereda.</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dra. Gladys Bao García</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 18753 RNE 14566</li>
                                        <li>
                                            <span itemprop="title">Médico especialista en Medicina Física y Rehabilitación</span>
                                        </li>
                                        <li>Médico de la Univ. Nacional Mayor de San Marcos</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Federico Villareal, Lima - Perú.</li>
                                        <li>Post Grado en Gerencia Hospitalaria en Univ. Cayetano Heredia, Lima - Perú.</li>
                                        <li>Diplomado en Evaluación de Proyectos de Investigación en Salud en Univ. San Martin de Porres</li>
                                        <li>Miembro de la Sociedad de Medicina de Rehabilitación del Perú</li>
                                        <li>Ponente en diversos eventos científicos sobre Medicina Física y Rehabilitación</li>
                                        <li>Profesora de Medicina Física y Rehabilitación en la Univ. Cayetano Heredia.</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dr. Renso Berlanga </span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP   42049 RNE 21823</li>
                                        <li>
                                            <span itemprop="title"> Médico especialista en Medicina Física y Rehabilitación</span>
                                        </li>
                                        <li>Médico de la Univ. Nacional de San Agustín de Arequipa</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Nacional Mayor de San Marcos.</li>
                                        <li>Amplia Experiencia Profesional en Rehabilitación Traumatológica</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dra. Gloria Flor Aldave Ayala </span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 27909 RNE 24194</li>
                                        <li>
                                            <span itemprop="title"> Médico especialista en Medicina Física y Rehabilitación</span>
                                        </li>
                                        <li>Médico de la Univ. Nacional Federico Villareal</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Nacional Mayor de San Marcos</li>
                                        <li>Post Grado en Salud Publica & Epidemiología. Univ. Nacional Federico Villareal.</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dra. Cielo Rivera Dávila</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 47019</li>
                                        <li><span itemprop="title"> Médico especialista en Medicina Física y Rehabilitación</span></li>
                                        <li>Médico de la Univ. Ricardo Palma</li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Federico Villareal, Lima - Perú.</li>
                                        <li>Diplomado en Salud Ocupacional en Univ. Nacional Mayor de San Marcos</li>
                                        <li>Diplomado en Dirección en Salud Publica y Hospitales en Univ. Nacional de Trujillo</li>
                                        <li>Diplomado en Gestión y Auditoria Médica en Univ. Nacional de Trujillo</li>
                                        <li>Ponente en diversos eventos científicos sobre Medicina Física y Rehabilitación</li>
                                        <li>Profesora de Medicina en la Univ. San Martin de Porres.</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Dr. Jorge Chávez Zanabria</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>CMP 46651</li>
                                        <li><span itemprop="title"> Médico especialista en Medicina Física y Rehabilitación</span></li>
                                        <li>Medico de la Univ. San Martin de Porres. </li>
                                        <li>Residencia de Medicina Física y Rehabilitación en Univ. Ricardo Palma</li>
                                        <li>Diplomado en Auditoria Medica en los Servicios de Salud Pública y Privada - Univ. Ricardo Palma</li>
                                    </ul>
                                </div>
                            </div>

                            <div id="sub-especialidad" style="margin-top:15px;" ><h2 style="font-seze:16px;" ><strong>FISIOTERAPEUTAS & ACUPUNTURA</strong></h2></div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Luz María Suarez Claros - Directora de Terapia OSI</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title"> Lic. Tecnólogo Médico especialista en Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Nacional Federico Villareal - Lima, Perú</li>
                                        <li>30 años de experiencia profesional en servicio de Medicina Física y Rehabilitación</li>
                                        <li>En Ministerio de Salud – Hospital Arzobispo Loayza, clínicas, Centro especializados.</li>
                                        <li>16 años en docencia en la Universidad Federico Villarreal – Terapia Física y Rehabilitación</li>
                                        <li>Expositor de conferencia, consultor de compañías de Seguro, Minería, Constructoras, Industria, Bancos, Comercio, etc.</li>

                                    </ul>
                                </div>
                            </div>
                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Lucia Matos Meza - Coordinadora de Terapia OSI</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title"> Lic. Tecnólogo Médico especialista en Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Univ. Peruana Cayetano Heredia - Lima, Perú</li>
                                        <li>Especialista en acupuntura con amplia experiencia en pacientes neurológicos.</li>
                                        <li>Máster en Medicina Tradicional China & Acupuntura - Univ. Europea Miguel de Cervantes - Valladolid, España </li>
                                        <li>Stage de Acupuntura y Medicina China en Taiwan International Healthcare Training Center - Taiwan, China.</li>
                                        <li>Invitada por diversos programas periodísticos para tratar temas de Medicina Alternativa.</li>
                                        <li>Ha participado en Emprendimientos de Responsabilidad e Inclusión Social. ONG ALDEIAS - Brasil.</li>
                                        <li>Ha participado en Proyecto de Salud Preventiva e Inclusión Social de GERACAO - Brasil.</li>
                                        <li>Ha dictado más de 200 charlas sobre salud preventiva para los principales clientes de las compañías de Seguro y EPS Pacifico y Rímac.</li>


                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. María Amparo Martínez</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Nacional Federico Villareal - Lima, Perú</li>
                                        <li>35 años de experiencia profesional en Fisioterapia y Rehabilitación en Perú y Estados Unidos. </li>
                                        <li>Diplomados en Estimulación Temprana & Neuropsicología Clínica</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Karina Rojas Colán</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Univ. Peruana Cayetano Heredia</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Abraham Munárriz Ticona</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Univ. Nacional Federico Villareal</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Mayra Salinas Calderón</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Univ. Peruana Cayetano Heredia</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Brenda Leyva Román</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li><span itemprop="title">  TM. Terapia Física y Rehabilitación.</span></li>
                                        <li>Univ. Peruana Cayetano Heredia</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Gustavo Zuñiga Olivares</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li><span itemprop="title">  TM. Terapia Física y Rehabilitación.</span></li>
                                        <li>Universidad Mayor de San Marcos</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Diana Ramírez</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Privada Norbert Wiener.</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Rodolfo Guillen Tello</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li><span itemprop="title">  TM. Terapia Física y Rehabilitación.</span></li>
                                        <li>Universidad Privada Norbert Wiener.</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Cindy Arenas Salazar</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Particular de Chiclayo</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Karen Leon</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Privada Norbert Wiener.</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Juan Carlos Aguilar Berchelde</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li><span itemprop="title">  TM. Terapia Física y Rehabilitación.</span></li>
                                        <li>Universidad Privada Norbert Wiener.</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Roxana Quispe</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">  TM. Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Universidad Privada Norbert Wiener.</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Lic. Yesica Calavero Poma</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li><span itemprop="title">  TM. Terapia Física y Rehabilitación.</span></li>
                                        <li>Universidad Alas Peruanas </li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Yakelin Luciano Rojas</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Blanca Rueda Tumay</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Elizabeth Sánchez</span>
                                    </div>
                                </div>
                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico Arzobispo Loayza</li>
                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">
                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Gisela Escalante</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title"> Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Linda Luna</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico Arzobispo Loayza</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Mariel Azucena Inocente</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Elizabeth Álvarez Flores</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Joselin Lucero Gonzales</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico Arzobispo Loayza</li>

                                    </ul>
                                </div>
                            </div>

                            <div class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Dana Quiroga Sivirichi</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico Arzobispo Loayza</li>

                                    </ul>
                                </div>
                            </div>

                            <div style="margin-bottom:30px;" class="doctor">

                                <div class="sub-especialidad2">
                                    <div style="color:#0083B4;font-size:15px;font-family: 'verlaglight';padding-bottom:3px;font-weight:bold;" itemscope itemtype="http://data-vocabulary.org/Person">
                                        <span itemprop="name">Tec. Maria Claudia Fernandez</span>
                                    </div>
                                </div>

                                <div class="simbolo" style="display:block;" ><img src="images/mas.png" width="9" height="9" /></div>
                                <div class="simbolo2" style="display:none;"><img src="images/menos.png" width="9" height="9" /></div>
                                <div class="staff-detalle" style="display:none;">
                                    <ul>
                                        <li>
                                            <span itemprop="title">Terapia Física y Rehabilitación.</span>
                                        </li>
                                        <li>Inst. Sup. Tecnológico de la Clínica R. Palma</li>

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
